### PR TITLE
Closes i-RIC/prepost-gui#409

### PR DESCRIPTION
**Pull request by kskinoue0612**
You can test this pull requests with the following precedure:

1. Open the issue-409.ipro, that is included in issue-409.zip attached below.
2. Delete the grid
3. Save the project
4. Open the project again
5. Make sure that the grid is deleted.

[issue-409.zip](https://github.com/i-RIC/prepost-gui/files/2434214/issue-409.zip)

### CODE REVIEW

**Comment by kskinoue0612** [comment]
This pull request includes some refactoring modifications on PreProcessorGridDataItem. The objective is to make the header file clean and easy to read.

**Comment by scharlton2** [comment]
Hi Keisuke,

I'm getting the following on the Release build:

```
1>------ Build started: Project: iricPre, Configuration: Release x64 ------
1>  gridbirdeyewindowdatamodel.cpp
1>subwindow\gridbirdeyewindow\gridbirdeyewindowdatamodel.cpp(59): error C2027: use of undefined type 'vtkDataObject'
1>          c:\iricdev\lib\install\vtk-6.1.0\debug\include\vtk-6.1\vtkAlgorithm.h(40) : see declaration of 'vtkDataObject'
1>subwindow\gridbirdeyewindow\gridbirdeyewindowdatamodel.cpp(59): error C2065: 'FIELD_ASSOCIATION_POINTS' : undeclared identifier
1>subwindow\gridbirdeyewindow\gridbirdeyewindowdatamodel.cpp(242): error C2027: use of undefined type 'vtkPointSet'
1>          c:\iricdev\lib\install\vtk-6.1.0\debug\include\vtk-6.1\vtkPointSetAlgorithm.h(36) : see declaration of 'vtkPointSet'
1>subwindow\gridbirdeyewindow\gridbirdeyewindowdatamodel.cpp(242): error C2227: left of '->GetBounds' must point to class/struct/union/generic type
2>------ Build started: Project: iricGui, Configuration: Release x64 ------
2>LINK : fatal error LNK1181: cannot open input file '..\pre\release\iricPre.lib'
3>------ Build started: Project: iricPython, Configuration: Release x64 ------
3>LINK : fatal error LNK1181: cannot open input file '..\pre\release\iricPre.lib'
========== Build: 0 succeeded, 3 failed, 46 up-to-date, 0 skipped ==========

```
The Debug build builds and works fine.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your information.

I’m sorry, I’ve checked only with debug mode. I’ll check and fix soon.

Thanks,

Keisuke

2018年10月2日(火) 9:46 Scott Charlton <notifications@github.com>:

**Comment by kskinoue0612** [comment]
Hi Scott,

I've checked, and fixed the code.

I've also rebased the issue-409 branch onto master branch, because there was a collision in libs/gui/languages/iricGui_a_JP.qm.

Thanks,
Keisuke

**Pull request merged**
