### PR TITLE
Closes i-RIC/prepost-gui#581

### PR DESCRIPTION
**Pull request by kskinoue0612**
Please use the following files for testing:

## post2d window (structured)

test_2d_structured.ipro attached to this.

## post2d window (unstructured)

SToRM tutorial data downloaded from below.

https://i-ric.org/en/download-file/?dlkey=ad8451edc29f33b32e70642abc368cad

Please run Run07.exe in Tutorial_2 folder to extract Run07. It is
a project folder with calculation result, and you can use it for testing.

## post3d windoww

test_3d.ipro attached to this.

Please note that, to make the file small, it does not contain calculation result. Please run the solver before you use it for testing.

# Screenshots

The screenshots for each functions are shown below.

## post2d window (structured)

screenshot-2d-structured

## post2d window (unstructured)

screenshot-2d-unstructured

## post3d windoww

screenshot-3d

[issue-581.zip](https://github.com/i-RIC/prepost-gui/files/3930520/issue-581.zip)

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

Looks good except that I found a bug in the unstructured grid (Storm).  It looks like it's always been there, but since you just worked on it I thought it would be easier to fix now.

For Run07 note that the second group of points (red) is not transported:

image

image

image

image

image


Thanks,
Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

Please ignore the previous comment, I wasn't careful enough when drawing the second group of particles.

Thanks,
Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

When opening a project that already contains a calculation result the particles for the first time step are not visible.

Previous Dev version (3.0.18.6297):

image

image


This version (edebb314):

image

image

Have a happy new year,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Happy new year!
Thanks for reporting the issue.

I've checked out https://github.com/i-RIC/prepost-gui/commit/edebb314802170675c6246e8f7f74d4485b5044a, built it, but I did not succeed to reproduce the issue.

What I've tried is as follows.
1. Open test_2d_structured.ipro
2. Open post2d window
3. Check on "Particles (auto)" -> "Velocity(ms-1)" in Object browser
4. Click on "Reset" button on animation toolbar, to move to step "0.1 sec"
5. Close post2d window
6. Open new post2d window, and check on "Particles (auto)" -> "Velocity(ms-1)"

On my PC, in step 4 and 6, particles are shown correctly.
Do I miss some steps to reproduce the issue?

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Sorry, I misinterpreted what was going wrong.


Steps to reproduce (using edebb314 version):
1. Open test_2d_structured.ipro from issue-581.zip
2. Open new 2D Post-Processing Window
3. Select (check) iRICZone->Particles (auto)->Velocity(ms-1)
4. Right-click on iRICZone->Particles (auto) and select Property...
5. Select 'Generate at arbitrary time' radio button
6. Press Edit... button
7. Add 0.1, 0.2, and 0.3 timesteps

image

8. Press OK, OK and Save the file as 'test_2d_structured123.ipro'
9. Start a new Project
10. Re-Open 'test_2d_structured123.ipro'
11. On the Post-processing (2D) window, Right-click on iRICZone->Particles (auto) and select Property...
12. Press the Edit... button
13. Note that the 0.1 sec time step is missing:

image

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your information.
I've succeeded to reproduce the issue you've reported.
I will fix it.

It seems that the branch has conflicts with master branch now, so I'll rebase issue-581 branch to master, add a fix commit, and push to my repository with -f option, so that you can merge it with "Merge pull request" button.

Thanks,

Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I've pushed commits to fix the issue. Please check it.

Thanks,
Keisuke

**Pull request merged**
