### PR TITLE
Close #503

### LINKED ISSUE #503: Geographic Data Colorbars Visibility not serialized correctly
When a file containing a Colorbar is saved and reopened the colorbar is not visible and the position is reset.

## Before closing file
image

## After reopening file
image

## After setting colorbar to be visible
image

[fastmech_tut1_ex1.zip](https://github.com/i-RIC/prepost-gui/files/3060304/fastmech_tut1_ex1.zip)

### PR DESCRIPTION
**Pull request by kskinoue0612**
Please test with the file attached to this pull request.

When the project file is opened, the color bar is loaded successfully.

[issue-503.zip](https://github.com/i-RIC/prepost-gui/files/6390968/issue-503.zip)

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

The scalarbar loses its location and size when it is saved and reopened when saved as not-visible.

Steps to reproduce:

Open the following ipro file:

[fastmech_tut1_ex1.zip](https://github.com/i-RIC/prepost-gui/files/3060304/fastmech_tut1_ex1.zip)

Turn on the scalarbar for Elevation and place it as shown:

image

Save as scalarbar-on.ipro:

image

Turn off scalarbar and save it as scalarbar-off.ipro

image

Reopen scalarbar-on.ipro (works as expected):

image

Reopen scalarbar-off.ipro and turn on scalarbar (scalarbar is in wrong place and has wrong size):

image

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for testing,
I’ll check and fix it.

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I've fixed the issue. Please check with the following steps.

[fastmech_tut1_ex1_fixed.zip](https://github.com/i-RIC/prepost-gui/files/6395744/fastmech_tut1_ex1_fixed.zip)

1. Open the project in fastmech_tut_ex1_fixed.zip that is attached to this comment.
2. Select "Elevation", open "Set Up scalarbar", check on "Visible" check box, and click on "OK" button.
3. Scalar bar is shown in the position saved in project file, like shown below.

Thanks,

Keisuke

screenshot

**Comment by kskinoue0612** [comment]
Thank you!

keisuke

**Pull request merged**
