### PR TITLE
Closes #741

### LINKED ISSUE #741: Add function to import *.tif and *.asc to integer type grid attributes.

### PR DESCRIPTION
**Pull request by kskinoue0612**
You can test this with the following procedure:

1. Start a new project for Nays2DH
2. Select "Geographic Data" / "Fixed or Movable Bed" in object browser
3. Select "Import" from right-clicking menu
4. Import issue-741.asc with this branch.
5. Please select "EPSG: 2450" for coordinate system.

Then, you'll see that issue-741.asc is imported successfully.

[issue-741.zip](https://github.com/i-RIC/prepost-gui/files/4819321/issue-741.zip)

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

This is a "New function" issue isn't it?  I think you meant to merge to the develop branch.  I think we should change the default branch to develop since it might avoid these type of mistakes:

https://github.com/i-RIC/prepost-gui/settings/branches

Thanks
Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

Did you read the integer raster as GDT_Float64 on purpose (instead of GDT_Int32) ? Maybe so that if the user tried to read a float/double raster into an integer/enum GeoData it would still work?

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

> Hi Keisuke,
> 
> This is a "New function" issue isn't it? I think you meant to merge to the develop branch. I think we should change the default branch to develop since it might avoid these type of mistakes:

Thank you for the notification. That's true. I'll merge the branch to develop branch manually, and close this pull request manually when it becomes OK.

Based on your suggestion, I've changed the default branch to "develop", so I guess we can avoid mistakes.

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

> Did you read the integer raster as GDT_Float64 on purpose (instead of GDT_Int32) ? Maybe so that if the user tried to read a float/double raster into an integer/enum GeoData it would still work?

Thank you for your comment.

The reason that I chose to read the integer raster value as GDT_Float64 instead of GDT_Int32 is that GDALRasterBand::GetNoDataValue() returns double value. I imagined that it is safer to read both NoDataValue and Value as double, and compare them.

And, yes, I also imagined maybe for some integer values, it may be helpful that we can import raster data with double values into integer grid attributes by casting. 

 Maybe we can just do like below. It will give the same result, and the code looks more natural.

```
int noDataValue = static_cast<int> (band->GetNoDataValue(&noDataSuccess))
std::vector<int> buffer1(bufSize);
band->RasterIO(GF_Read, 0, 0, data->xSize(), data->ySize(), buffer1.data(), data->xSize(), data->ySize(), GDT_Int32, 0, 0);
```
It will work for *.tif, *.asc with real values with no error, because GDALRasterBand::RasterIO() convert data automatically. Please see the document below.

> eBufType | the type of the pixel values in the pData data buffer. The pixel values will automatically be translated to/from the GDALRasterBand data type as needed.

https://gdal.org/doxygen/classGDALRasterBand.html#a75d4af97b3436a4e79d9759eedf89af4

What do you think? If you agree, I'll modify the code in that way.

Thanks,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I didn't notice the cast on the noDataValue variable.  I think it's OK to leave it as is.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for your comment. OK.
I'll merge this branch to develop, and close this pull request.

Thanks,
Keisuke

**Pull request closed without merging**
