### PR TITLE
Close #1107

### LINKED ISSUE #1107: Add function to import source text into Textarea on input condition dialog

### PR DESCRIPTION
**Pull request by kskinoue0612**
Add function to import source text into Textarea on input condition dialog

[issue-1107.zip](https://github.com/i-RIC/prepost-gui/files/10715045/issue-1107.zip)

### CODE REVIEW

**Comment by kskinoue0612** [comment]
Hi Scott,

Can you check the function, please?
I think maybe the function will be benefitial when you implement new solvers to iRIC.
issue-1107.zip includes definition.xml etc, so unzip it and put it to "solvers" folder to test.

Thank you,

Keisuke Inoue

**Comment by kskinoue0612** [comment]
Hi Scott,

 I've noticed that build fails with Release mode, so I've pushed another commit.

Thank you,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I need to work on the appveyor build.  Pull requests can't use secure variables so the following needs to be updated:
https://github.com/i-RIC/prepost-gui/blob/develop_v4/appveyor.yml#L200..L213

Unauthorized calls to github's rest api are limited (I think by IP address) and since a lot of calls are made from appveyor's IP addresses they sometimes fail.

Maybe we can create another (un-encrypted) access_token that has read-only access.

I'll take a look at it tomorrow.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for working on this. I understand.
Not in a hurry, so no problem.

Thank you,

Keisuke

2023年2月13日(月) 13:09 Charlton, Scott R. ***@***.***>:

**Comment by scharlton2** [comment]
Hi Keisuke,

I added a read-only access token (i-RIC/iricdev-2019/releases) here:

https://github.com/organizations/i-RIC/settings/personal-access-tokens/active

I disguised it in a base64 string in the appveyor file.  It has to be renewed in a year.

The PR looks good.  I'll merge it now.

Thanks,
Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

I just noticed that your release build still isn't building.  If you want it to build on your repo, you'll need to set the secure env variable `kskinoue0612_json_pw` in the appveyor.yml file (replace the todo string with the password you normally use when sending zip files).

I think this is the url you would use to encrypt the password:

https://ci.appveyor.com/account/kskinoue0612//tools/encrypt

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for the information. OK, I'll do it!

Thank you,

Keisuke

**Pull request merged**
