### PR TITLE
Closes #793, #817

### LINKED ISSUE #793: Add function to import or export polygon groups, polyline groups, point groups from/to CSV files
Add function to export polygons, polylines, points from / to CSV files.

We want to make it simple, this is for users who wants to create data manually. So, maybe we will not implement polygons with holes. That will the file format too complex.

Image below shows the file formats for polygon groups, polyline groups, and point groups.

formats

### PR DESCRIPTION
**Pull request by kskinoue0612**
# Issue 817

Add function to export / import "Polygon group", "Polyline group", "Point group" from / to CSV files.

You can test with issue-817.zip attached to this.

# Issue 793

When a point in point group is selected, please select "Edit coordinates" from right-clicking menu.
Without the commits, nothing happens. On this branch, dialog to edit coordinate values are shown.

# Other issues

The following misc bugs are also fixed with this pull request:
* Offset values were not handled properly with "Point group", "Polyline group" and "Polygon group".
* When "Point group" is exported to shape files, offset values were not handled properly.  
* When a polyline in "Polyline group" is selected, "Add vertex", "Remove vertex", "Edit coordinates" menus are not enabled.

[issue-817.zip](https://github.com/i-RIC/prepost-gui/files/5371924/issue-817.zip)

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

I don't think it's handling the offset right.  I think that when exporting that the files should be the same with or without an offset:
image
image

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for reviewing the pull request, and the information.
I’m sorry, I thought I’ve tested enough about offset, but maybe not.

I will check again about offset. I guess I can check within this week.

Thank you,

Keisuke Inoue

2020年11月1日(日) 4:01 Scott Charlton <notifications@github.com>:

**Comment by kskinoue0612** [comment]
Hi Scott,

I've tested about offset.
As long as I've tested, it looks to me that it's working correctly.
I'm afraid maybe the way I've tested is different from yours.

I've tested in the way below:

1. Start a new project (at this point offset is (0, 0)).
2. Import points/lines/polygons from points.csv etc. attached to this comment.
3. Export data to CSV file, and make sure that it is the same to file imported in step 2.
4. Open File -> Property menu, and edit offset to (1000, 1000), for example.
5. Export data to CSV file, and make sure that it is the same to file imported in step 2.

[testdata.zip](https://github.com/i-RIC/prepost-gui/files/5479080/testdata.zip)

Can you make sure, and give information about the way to reproduce the issue you found?

Thanks,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Sorry, I am not able to reproduce the results I got earlier.  I still have the previous projects, and they still give the same results as above.

I might have been running an incomplete build previously because of the bad QMAKE_POST_LINK command fixed by #832.

I did find a problem with the 'Edit Coordinates' dialog:

1. Open issue-817
2. Set an offset of (2,3)
3. In Object Browser select Geographic Data->Reference Information->Point Group1
4. In Attribute Browser select Point8
5. Right-click in main view area of Pre-processing Window and select 'Edit Coordinates'
6. Note the value should be X = -1.052 Y = -0.144

image

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for the information.
I’m going to fix the bug on the coordinate edit function.

Thank you,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I also noticed that if the offset is set while a point, polygon, or polyline is selected, its position doesn't get updated:

1. Open issue-817
2. Select Geographic Data -> Reference Information -> Polygon Group1 in the Object Browser
3. In the Polygon Group Attribute Browser select Polygon3
4. File->Property...->Offset-> X: 2 Y: 0

image

image

image

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for the information, and I’m sorry for the bug. I’ll fix the bug too.

Thanks,

Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I've fixed the bugs you reported. I also found a few new bugs, and fixed them too.
Thank you,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Sorry to take so long on this one.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

It’s OK,
Thank you for your detailed testing and reviewing.

Thanks,
Keisuke

**Pull request merged**
