### PR TITLE
Closes i-RIC/prepost-gui#74

### PR DESCRIPTION
**Pull request by scharlton2**
Hi Keisuke,

Here is the cleaned up version along with some files to test with.

[structured.zip](https://github.com/i-RIC/prepost-gui/files/2908485/structured.zip)

[unstructured.zip](https://github.com/i-RIC/prepost-gui/files/2908558/unstructured.zip)

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

Don't bother reviewing yet.  I discovered a problem with the unstructured cell-centered graph.  I'll try to fix it as soon as I can.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for the pull request.
I’m out of my office this afternoon, and I think I can review it tonight.

Thanks,

—
Keisuke Inoue

2019年2月27日(水) 13:22 Scott Charlton <notifications@github.com>:

**Comment by scharlton2** [comment]
Hi Keisuke,

I think everything should be working now.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for the pull request. It worked perfectly.

I'm sorry for the last inappropriate comment. I've knew the pull request by reading the mail to gmail, and did not noticed your comment after you've opened the pull request.

Anyway, thank you very much!
--
Keisuke

**Pull request merged**
