### PR TITLE
Closes i-RIC/prepost-gui#706

### PR DESCRIPTION
**Pull request by kskinoue0612**
You can test this pull request with the follwing steps:

## User can edit the names of each polygon

1. Start a project for Nays2DH
2. Select "Geographic Data" -> "Elevation (m)" in Object Browser
3. Select menu "Geographic data" -> "Polygon" -> "Add New Polygon"
4. Define polygon with mouse clickings, and enter "Elevation (m)" value
5. After defining polygon, select menu "Edit name and Value" from right-clicking menu

On the dialog, user can now edit name and value at once.

## User can edit name and value for multiple polygons at once

1. Open case1.ipro in issue-706.zip
2. Select "Geographic Data" -> "Elevation (m)" -> "Polygon1" in Object Browser
3. Select multiple polygons by mouse dragging
4. Select menu "Edit name and Value" from right-clicking menu
5. Input Name and Elevation (m) value, and click on "OK".

You can check that name ane value for selected polygons are changed at once.

## "Attribute browser" is added

You can see "Polygons Attribute Browser" on pre-processor window, when a polygon is added.
You can edit name and value on the attribute browser, by mouse-clicking on Name and Value.

When "Show" button is clicked, Pre-processor window pan to the center of the polygon bounding box.

Selection on pre-processor window and attribute browser synchronizes.

## User can sort the order of polygons

1. Open case2.ipro in issue-706.zip
2. Select "Geographic Data" -> "Elevation (m)" -> "Polygon1" in Object Browser
3. Select polygon by mouse dragging or clicking
4. You can change the order of polygons with right clicking menu "Sort" -> "Move to top" etc.

"Move to top", "Move to bottom" are enabled when polygons are selected.
"Move up", "Move down" are enabled when polygons are selected, and polygons are continuous on attribute browser. For example when 1st and 2nd polygon is selected they are enabled, but when 1st and 3rd polygon is selected they are disabled.

When the order is changed, you can check that the change affects the result of mapping to grid. When multiple polygons exists at a grid node position, the polygon on the top is mapped.

## Import interface improvement

1. Start a project for Nays2DH
2. Select "Geographic Data" -> "Elevation (m)" in Object Browser
3. Select "Import" from right-clicking menu.
4. Select "importtest.shp", and click on "Open" button.

With older "iRIC (develop)", users were asked to select from "ESRI Shapefile (Polygon)" or
"ESRI Shapefile (Polygon group)". With this branch, the dialog does not appear, and the data is imported as polygon group.

## Old projects support

Old style polygon is deprecated, and user can now add polygon group only. But, old style polygons can be loaded from projects created with older versions.

You can check this by opening case3.ipro. It is a project file created with old iRIC GUI,
and includes old style polygon data.

[issue-706.zip](https://github.com/i-RIC/prepost-gui/files/4501826/issue-706.zip)

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

"Import interface improvement" section

I noticed when importing "importtest.shp" that the Polygon Attribute Browser did not get updated until I clicked in the Graphic View:

image

"Old projects support" section

When you say that "user can now add polygon group only".  I'm assuming that you mean when importing a shape file with multiple polygons.  Because I can still create multiple polygons using either Geographic Data->Polygon->Add New Polygon or By Right-clicking a Geographic Data->Add->Polygon...

I noticed that when adding multiple Polygons that the Polygon Attribute Browser doesn't update the name of the selected polygon:

image

PS
iRIC crashed once when I was selecting a polygon within the Object Browser but, I was unable to reproduce it (I think it was in a release configuration).

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for testing the branch, and the feedback.
I think I can check and fix the issues in a few days.

When finished, I'll contact you again.
Thanks,

Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

> "Import interface improvement" section
> 
> I noticed when importing "importtest.shp" that the Polygon Attribute Browser did not get updated until I clicked in the Graphic View:

I've fixed this. Now when polygons are imported from shp file, the attribute browser is updated immediately. Thank you for the notification.

> "Old projects support" section
> 
> When you say that "user can now add polygon group only".  I'm assuming that you mean when importing a shape file with multiple polygons.  Because I can still create multiple polygons using either Geographic Data->Polygon->Add New Polygon or By Right-clicking a Geographic Data->Add->Polygon...
> 
> I noticed that when adding multiple Polygons that the Polygon Attribute Browser doesn't update the name of the selected polygon:

Thank you for the comment.

Actually, in the previous pull request, I pushed modification to rename "Polygon group" to "Polygon", because old style "Polygon" can not be added now. When we select menu "Add polygon", we were actually adding "Polygon group".

But thanks to your comment, I've noticed that it is confusing for users. I've pushed a commit (https://github.com/i-RIC/prepost-gui/pull/707/commits/8528e806ba25dc2341e868a2e44ca11ea2a53c78) to revert the change, and the menu "Add Polygon" is now "Add Polygon Group" again.

With the previous pull request, the Polygon groups were named "Polygon1", "Polygon2", etc., and each polygons in the groups are also named "Polygon1", "Polygon2", etc. It also was confusing, so I've made modification in https://github.com/i-RIC/prepost-gui/pull/707/commits/8528e806ba25dc2341e868a2e44ca11ea2a53c78, and now the polygon groups are named like "Polygon Group1", instead of "Polygon1".

I hope it is better now. If you have ideas about improvement to make the interface more clear, please let me know.

I've also pushed a few commits for improvements below:
* Now when "Show" button is clicked in attribute browser, the polygon is selected, so that it is easier to recognize which polygon's "show" button is clicked.
* For consistency, the information dialog is shown every time when polygon is added.

> PS
> iRIC crashed once when I was selecting a polygon within the Object Browser but, I was unable to reproduce it (I think it was in a release configuration).

While testing, I did not experienced iRIC crash. When we succeed to reproduce the issue, let's register and fix it.

Thanks,

Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I've noticed two more bugs, and pushed commits to fix them.
Sorry for bothering you.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

When creating a new polygon group, if you change the selection within the object browser before creating a new polygon, iRIC crashes.  Also, is there a way to delete a polygon from a polygon group? Seems that I could only delete the whole polygon group.

Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

> When creating a new polygon group, if you change the selection within the object browser before creating a new polygon, iRIC crashes. 

Thank you for the information, and I'm sorry for the bug.
I've fixed it, and pushed another commit.

> Also, is there a way to delete a polygon from a polygon group? Seems that I could only delete the whole polygon group.

Yes, there is. Please try the following procedure.
1. Select polygons in polygon groups, by mouse dragging to define bounding box.
2. Select "Delete" menu in Right-clicking menu.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

When undoing/redoing an "Edit Name and Value..." change for a single polygon selection, the "Polygon Group Attribute Browser" doesn't get updated.  I was able to fix this by adding an `emitNameAndValueEdited` function to `GeoDataPolygon` and calling it from the undo/redo functions of `GeoDataPolygon::EditNameAndValueCommand`.  I didn't create a pull request because I thought you might want to handle it differently.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for your comment.
I'm going to fix the issue in the way you suggested.

I feel that I did not test the new function precisely enough.
I'll test more, and fix issues if I find. I'll contact again when I feel I've tested enough.

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I've tested the branch, fixed several bugs, and made a few improvements.

May 2nd to 6th is a long national holidays in Japan (it is called "Golden Week"). I'll test the branch
again on 7th with clear mind, and if I do not find additional bugs, I'll push commits to this branch, and contact you.

Thanks,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Okay, have a good vacation.  Hopefully you can get out of the house.

Scott

**Comment by kskinoue0612** [comment]
Thank you, Scott!

Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I've pushed commits for fixing several bugs, making a few improvements, as below:

Thank you.
Keisuke

## Bug fix

* When undo "Edit name and value" command for polygon, "Polygon Group Attribute Browser" does not get updated.
* When polygon in "Reference Information" group's name is edited, and the operation is undoed, "Polygon Group Attribute Browser" is not updated.
* When single polygon is selected, other items in object browser is selected, polygon group is selected again, then user can not edit the polygon.
* When single polygon is selected, and it is sorted with "Move to top", "Move up", "Move down", "Move to bottom", it is not possible to edit the polygon.
* When polygon's vertex is removed, "Remove vertex" action's check status was not cleared.
* When new polygon is added, actions to sort (ex. "Move to top") were not enabled.
* When "Edit value" operation (that is executed when user finished polygon definition) is undoed, "Polygon Group Attribute Browser" is not updated.

# Improvements
* Previously, user had to select whole row in attribute browser to select a polygon. Now when one cell in attribute browser is selected, the polygon is selected.
* When "Show" button of polygon that is already selected is clicked, iRIC now just pans, and mergeEditTargetPolygon(), setupEditTargetPolygonFromSelectedPolygon() is not called. It improve performance.
* Editing name and value for multiple polygon is now undoable.
* Edit name and value operation in attribute browser is now undoable, when single row is selected. When user edit name or value while multiple rows are selected, that operation is not undoable.
* Editing name for multiple polygon (user can do this for polygon group in "Reference Information" group) is now undoable.

**Comment by scharlton2** [comment]
Hi Keisuke,

This is a strange bug.  It requires two undo(s).

1. Start a project for Nays2DH
2. Create a new Polygon Group under Elevation (m) containing at least two polygons
3. Select all of the polygons and select "Edit Name and Value" from right-click menu
4. Change the elevation.
5. Select a single polygon within the polygon group and select "Edit Name and Value" from the right-click menu.
6. Change the elevation
7. Press undo twice.  iRIC crashes in the QString operator = override.

I don't think this is related to my pull request but, you might want to try to reproduce before merging [my request.](https://github.com/kskinoue0612/prepost-gui/pull/17)

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for the report.
I'm sure that the issue is not related to your pull request, so I've merged it first.

I'm going to check and fix the issue.
Thank you.

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

The second undo doesn't reset the value to its original value  of 0:

Create polygroup with 3 polygons
image

Select all 3 polygons and change elevation to 20
image

Select Polygon1 and set elevation to 30
image

After setting Polygon1 elevation to 30
image


After 1st Undo
image

After 2nd Undo
image

## Appveyor artifacts

And I don't think we need the artifacts in appveyor.  Just comment them out with your next push:

Change:

```
artifacts:
  - path: libdlls\$(Configuration)
    name: libdlls-$(Configuration)
  - path: apps\iricgui\$(config)
    name: iricgui-$(Configuration)
```

To:

```
#artifacts:
#  - path: libdlls\$(Configuration)
#    name: libdlls-$(Configuration)
#  - path: apps\iricgui\$(config)
#    name: iricgui-$(Configuration)
```


Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

I've pushed commits to fix the issue.

As I've told in the web meeting, It seems not easy to fix it when multiple undos are enabled, so now when use select one polygon, undo stack is cleared.

Thanks,
Keisuke

**Pull request merged**
