### PR TITLE
Closes i-RIC/prepost-gui#691

### PR DESCRIPTION
**Pull request by kskinoue0612**
This closes three issues described in #691.

> * iRIC crashes when user do the following operation
>     1. Run a solver
>     2. Open a post2d (or post3d) window
>     3. Run the solver again

You can test with issue-691.zip attached to this pull request.

> * On Post3D window, label string is not properly updated when the time step changes.

You can test with https://yasu.i-ric.org/fw/3dtest.ipro.
I've tested with label setting declaration with:
* Concentration at (10, 10,  30) as Variable "C"
* Definition of output is as below:
```
return C.toFixed(10);
```

> * iRIC crashes when user do the following operation
>   1. Run a solver
>   2. Open a post2d (or post3d) window
>   3. Setup label to show grid node attribute
>   4. Generate a smaller size grid on post2d window
>   5. Run solver again

You can test with issue-691.zip attached to this pull request.
Please do the following operation.
1. Open issue-691.zip
2. Focus on Pre-processor window.
3. Select menu Grid -> Create Grid
4. Select "Channel Shape Parameters" group in "Grid Creation" dialog, and edit "Wave Number" from 2 to 1, and click on "Create Grid".
5. Select menu Grid -> Attributes Mapping -> Execute, and map Manning's roughness coefficient.
6. Run the solver again.

Older version crashes. The new version in this branch shows message "I, J, K, index for label is reset because the grid size is changed".

Currently, there is no solver that output result at cells and edges, so I've tested only with nodes.
I've checked the code of the the new functions of PostStringResultArgument in the following list carefully, and I think they should work.
* fixCellIndexIfNeeded()
* fixEdgeIIndexIfNeeded()
* fixEdgeJIndexIfNeeded()
* fixEdgeKIndexIfNeeded()

Thanks,
Keisuke

[issue-691.zip](https://github.com/i-RIC/prepost-gui/files/4347828/issue-691.zip)

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

Sorry, it took so long for me to review this.  We are being made to work from home now and it took me a while to get my laptop setup.  Everything seems to work except that I'm confused about one of the dialogs.

On the third test, after step 4 this dialog is shown:

image

Which I assumed (when answering yes) was the same as step 5.  Skipping step 5 yields an error in the solver.

Maybe, what's done in:
`void PreProcessorGridAttributeMappingSettingTopDataItem::customMapping(bool nomessage)`

should also be done in
`void PreProcessorGridAndGridCreatingConditionDataItem::informGridCreation()
`
Let me know if I'm getting something wrong.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your response.
I understand, because the situation is similar in Japan too. Currently I commute to my office as usual, but maybe tomorrow we are made to stay at home.

Anyway, thank you for your notification. I think you are right. When we click on “yes” button on “Do you want to map ...” dialog, mapping should be executed, so that we do not need to map manually.

I think it is a separate issue, so I registered another issue, as https://github.com/i-RIC/prepost-gui/issues/694.

If it is the only issue, please merge the pull request. I’m going to work on the issue in a separate branch.

Thank you.

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

When opening [edges-2.zip](https://github.com/i-RIC/prepost-gui/files/4370990/edges-2.zip) all indices get reset except for the nodes (you can see the original values using the develop version).  Also, when using the Debug configuration, if you resize the window you get another "I, J, K, index for label is reset because the grid size is changed." dialog and then iric crashes in the debugger in qvector.h.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for reporting the issues. I've pushed commits to fix them.
Thanks,

Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for reviewing and merging the pull request.

Thanks,
Keisuke

**Pull request merged**
