### PR TITLE
Close #869, #893, #894

### LINKED ISSUE #869: Add function to import 16bit Grayscale PNG as elevation data
Unreal Engine 4 uses Grayscale 16bit PNG for importing Raster DEM data.
To import and export DEM data created with Unreal engine 4, add function to import / export Grayscale 16bit PNG images, with metadata saved in world file etc.

### PR DESCRIPTION
**Pull request by kskinoue0612**
Please test with the following steps:

# Issue 869

## Test importing

1. Start a new project for Nays2DH
2. Select "Geographic data" -> "Elevation (m)"
3. Select "Import" from right-clicking menu
4. Select "test.png" and import it.
5. Dialog to select coordinate system for the geodata and project are shown. Select "WGS 84".
6. Make sure that the file is imported successfully, 

## Test exporting

1. Select the "Raster data1", and select "Export" from right-clicking menu.
2. Select Grayscale 16bit PNG files (\*.png), input filename, and click on "Save" button.
3. Make sure that \*.png, \*.pgw, \*.png.meta are output, and they are the same to the files imported.

# Issue 893 

1. Select the "Raster data1", and select "Export" from right-clicking menu.
2. Select "GeoTiff files (\*.tif)" or "ArcInfo ASCII files (\*.asc)", input filename, and click on "Save" button.
3. Make sure that a file is exported successfully.

# Issue 894

1. Select the "Raster data1", and select "Export" from right-clicking menu.
2. Select "NetCDF files (\*.nc)", input filename, and click on "Save" button.
3. Make sure that a file is exported successfully.

[issue-869.zip](https://github.com/i-RIC/prepost-gui/files/5930044/issue-869.zip)

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

Issue 893

It looks like GeoTiff and ArcInfo ASCII exports are inverted:

Original png:

image

Exported GeoTiff:

image

Exported ArcInfo:

image

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for fixing the English grammars, testing, and reporting the issue. 
I'm going to check and fix the issue.

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I've pushed a commit to fix the issue you've reported.
While testing I've noticed that the information about coordinate system is not exported properly, and fixed that too.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

# Issue 894

I don't know that much about netcdf, but shouldn't you be able to import the netcdf file that was exported for issue 894?  I'm getting:

image

when I try to import it to "Geographic data" -> "Elevation (m)".

I ran ncdump on the file and it seemed to have latitude and longitude:

```
netcdf netcdf {
dimensions:
	x = 4 ;
	y = 6 ;
variables:
	double x(x) ;
		x:long_name = "x-coordinate in Cartesian system" ;
		x:units = "m" ;
		x:axis = "X" ;
	double y(y) ;
		y:long_name = "y-coordinate in Cartesian system" ;
		y:units = "m" ;
		y:axis = "Y" ;
	double lon(y, x) ;
		lon:long_name = "Longitude" ;
		lon:units = "degrees_east" ;
	double lat(y, x) ;
		lat:long_name = "Latitude" ;
		lat:units = "degrees_north" ;
	double value(y, x) ;
data:

 x = 25, 75, 125, 175 ;

 y = 25, 75, 125, 175, 225, 275 ;

 lon =
  25, 75, 125, 175,
  25, 75, 125, 175,
  25, 75, 125, 175,
  25, 75, 125, 175,
  25, 75, 125, 175,
  25, 75, 125, 175 ;

 lat =
  25, 25, 25, 25,
  75, 75, 75, 75,
  125, 125, 125, 125,
  175, 175, 175, 175,
  225, 225, 225, 225,
  275, 275, 275, 275 ;

 value =
  13, 5, 1, 20,
  88, 75, 27, 9,
  32, 42, 50, 6,
  3, 8, 35, 10,
  40, 20, 100, 36,
  1, 3, 5, 2 ;
}
```

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for the testing.

I agree with you, we should make it possible to import NetCDF files into
iRIC, that we've exported from iRIC. Sorry, I did not test importing. I'll
look into the code of importing NetCDF files.

Thanks,

Keisuke


2021年2月9日(火) 0:48 Scott Charlton <notifications@github.com>:

**Comment by kskinoue0612** [comment]
Hi Scott,

I've fixed the function to import NetCDF file, so that we can import files exported from iRIC.

I've also made sure that I did not break the original function to import NetCDF file with time dimension.

You can test with the following steps:
1. Download https://www.unidata.ucar.edu/software/netcdf/examples/tos_O1_2001-2002.nc
2. Create project for Nays2dflood
3. import tos_O1_2001-2002.nc to Xrain
4. export data to *.nc
5. import the exported file, and make sure it is identical to data imported in 3.

Thanks,

Keisuke

**Pull request merged**
