### PR TITLE
Closes i-RIC/prepost-gui#234

### PR DESCRIPTION
**Pull request by kskinoue0612**

### CODE REVIEW

**Comment by kskinoue0612** [comment]
Hi Scott,

Please use the attached file to test this pull request.

Thanks,
Keisuke

[testdata.zip](https://github.com/i-RIC/prepost-gui/files/1606349/testdata.zip)

**Comment by scharlton2** [comment]
Hi Keisuke,

Triggering the generated attributes crashed both generators.  Did you make any changes to IRICLIB.DLL?  I'm currently using the latest version (iriclib-139cd84).


Trigger Grid -> Attribute Generating --> Generate Acc:

image

With the following output from Depends.exe:
```
Warning: At least one delay-load dependency module was not found.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.

--------------------------------------------------------------------------------
Starting profile on 1/12/2018 at 4:59:33 PM

Operating System: Microsoft Windows NT/2000/XP/2003/Vista based Enterprise (64-bit), version 6.01.7601 Service Pack 1
Program Executable: c:\prepost-gui\apps\gridattrgenerators\IRIC_ACC.EXE
Program Arguments: C:/Users/charlton/.iRIC_workspace/d23ab2b963d038748f9545a5540e7dfa/c133ae9c4636f8cc93c02569671f8d82 Acc ""
Starting Directory: c:\prepost-gui\apps\gridattrgenerators\
Search Path: c:\prepost-gui\apps\iricgui\release;C:\prepost-gui\libdlls\release;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\;C:\Program Files (x86)\MSBuild\12.0\bin;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\x86_amd64;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\VCPackages;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools\x64\;C:\Qt\5.5\msvc2013_64\bin;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\Perl64\site\bin;C:\Perl64\bin;C:\Tcl\bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\mpirt;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32\mpirt;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32\compiler;C:\Program Files\CollabNet\Subversion Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\7-Zip;C:\Program Files (x86)\GnuWin32\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\CMake\bin;C:\bin;C:\php-7.1.5-Win32-VC14-x64;C:\Program Files\doxygen\bin;C:\Program Files (x86)\Graphviz2.38\bin;C:\Program Files\USGS\vs2drt-1.3.0\bin;C:\Program Files\Git\cmd

Options Selected:
     Log DllMain calls for process attach and process detach messages.
     Hook the process to gather more detailed dependency information.
     Log LoadLibrary function calls.
     Log GetProcAddress function calls.
     Log first chance exceptions.
     Log debug output messages.
     Automatically open and profile child processes.
--------------------------------------------------------------------------------

Started "IRIC_ACC.EXE" (process 0xE28) at address 0x000000013F780000.  Successfully hooked module.
Loaded "NTDLL.DLL" at address 0x0000000077970000.  Successfully hooked module.
Loaded "KERNEL32.DLL" at address 0x0000000077750000.  Successfully hooked module.
Loaded "KERNELBASE.DLL" at address 0x000007FEFD750000.  Successfully hooked module.
DllMain(0x000007FEFD750000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNELBASE.DLL" called.
DllMain(0x000007FEFD750000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNELBASE.DLL" returned 1 (0x1).
DllMain(0x0000000077750000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNEL32.DLL" called.
DllMain(0x0000000077750000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNEL32.DLL" returned 1064829185 (0x3F780101).
...
DllMain(0x000007FEE9B60000, DLL_PROCESS_ATTACH, 0x000000000016F8F0) in "MSVCR120.DLL" returned 1 (0x1).
DllMain(0x000007FEE9C50000, DLL_PROCESS_ATTACH, 0x000000000016F8F0) in "MSVCP120.DLL" called.
DllMain(0x000007FEE9C50000, DLL_PROCESS_ATTACH, 0x000000000016F8F0) in "MSVCP120.DLL" returned 1 (0x1).
DllMain(0x0000000059B90000, DLL_PROCESS_ATTACH, 0x000000000016F8F0) in "QT5CORE.DLL" called.
DllMain(0x0000000059B90000, DLL_PROCESS_ATTACH, 0x000000000016F8F0) in "QT5CORE.DLL" returned 1 (0x1).
DllMain(0x000007FEE38B0000, DLL_PROCESS_ATTACH, 0x000000000016F8F0) in "ZLIB.DLL" called.
DllMain(0x000007FEE38B0000, DLL_PROCESS_ATTACH, 0x000000000016F8F0) in "ZLIB.DLL" returned 1 (0x1).
DllMain(0x000007FEE3890000, DLL_PROCESS_ATTACH, 0x000000000016F8F0) in "SZIP.DLL" called.
DllMain(0x000007FEE3890000, DLL_PROCESS_ATTACH, 0x000000000016F8F0) in "SZIP.DLL" returned 1 (0x1).
DllMain(0x000007FEE38D0000, DLL_PROCESS_ATTACH, 0x000000000016F8F0) in "HDF5.DLL" called.
DllMain(0x000007FEE38D0000, DLL_PROCESS_ATTACH, 0x000000000016F8F0) in "HDF5.DLL" returned 1 (0x1).
DllMain(0x000007FEE2140000, DLL_PROCESS_ATTACH, 0x000000000016F8F0) in "CGNSDLL.DLL" called.
DllMain(0x000007FEE2140000, DLL_PROCESS_ATTACH, 0x000000000016F8F0) in "CGNSDLL.DLL" returned 1 (0x1).
DllMain(0x000007FEE3850000, DLL_PROCESS_ATTACH, 0x000000000016F8F0) in "IRICLIB.DLL" called.
DllMain(0x000007FEE3850000, DLL_PROCESS_ATTACH, 0x000000000016F8F0) in "IRICLIB.DLL" returned 1 (0x1).
First chance exception 0xC0000005 (Access Violation) occurred in "IRIC_ACC.EXE" at address 0x000000013F78410B.
Second chance exception 0xC0000005 (Access Violation) occurred in "IRIC_ACC.EXE" at address 0x000000013F78410B.
Exited "IRIC_ACC.EXE" (process 0xE28) with code 62097 (0xF291).
```

Trigger Grid -> Attribute Generating --> Generate Dir:

image

With the following output from Depends.exe:
```
Warning: At least one delay-load dependency module was not found.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.

--------------------------------------------------------------------------------
Starting profile on 1/12/2018 at 5:15:10 PM

Operating System: Microsoft Windows NT/2000/XP/2003/Vista based Enterprise (64-bit), version 6.01.7601 Service Pack 1
Program Executable: c:\prepost-gui\apps\gridattrgenerators\IRIC_DIR.EXE
Program Arguments: C:/Users/charlton/.iRIC_workspace/d23ab2b963d038748f9545a5540e7dfa/9186f49874ce1931b7f5bc783da1517c Dir ""
Starting Directory: c:\prepost-gui\apps\gridattrgenerators\
Search Path: c:\prepost-gui\apps\iricgui\release;C:\prepost-gui\libdlls\release;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\;C:\Program Files (x86)\MSBuild\12.0\bin;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\x86_amd64;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\VCPackages;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools\x64\;C:\Qt\5.5\msvc2013_64\bin;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\Perl64\site\bin;C:\Perl64\bin;C:\Tcl\bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\mpirt;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32\mpirt;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32\compiler;C:\Program Files\CollabNet\Subversion Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\7-Zip;C:\Program Files (x86)\GnuWin32\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\CMake\bin;C:\bin;C:\php-7.1.5-Win32-VC14-x64;C:\Program Files\doxygen\bin;C:\Program Files (x86)\Graphviz2.38\bin;C:\Program Files\USGS\vs2drt-1.3.0\bin;C:\Program Files\Git\cmd

Options Selected:
     Log DllMain calls for process attach and process detach messages.
     Hook the process to gather more detailed dependency information.
     Log LoadLibrary function calls.
     Log GetProcAddress function calls.
     Log first chance exceptions.
     Log debug output messages.
     Automatically open and profile child processes.
--------------------------------------------------------------------------------

Started "IRIC_DIR.EXE" (process 0x147C) at address 0x000000013F9C0000.  Successfully hooked module.
Loaded "NTDLL.DLL" at address 0x0000000077970000.  Successfully hooked module.
Loaded "KERNEL32.DLL" at address 0x0000000077750000.  Successfully hooked module.
Loaded "KERNELBASE.DLL" at address 0x000007FEFD750000.  Successfully hooked module.
DllMain(0x000007FEFD750000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNELBASE.DLL" called.
DllMain(0x000007FEFD750000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNELBASE.DLL" returned 1 (0x1).
DllMain(0x0000000077750000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNEL32.DLL" called.
DllMain(0x0000000077750000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNEL32.DLL" returned 1067188481 (0x3F9C0101).
...
DllMain(0x000007FEE9B60000, DLL_PROCESS_ATTACH, 0x000000000028F4D0) in "MSVCR120.DLL" returned 1 (0x1).
DllMain(0x000007FEE9C50000, DLL_PROCESS_ATTACH, 0x000000000028F4D0) in "MSVCP120.DLL" called.
DllMain(0x000007FEE9C50000, DLL_PROCESS_ATTACH, 0x000000000028F4D0) in "MSVCP120.DLL" returned 1 (0x1).
DllMain(0x0000000059B90000, DLL_PROCESS_ATTACH, 0x000000000028F4D0) in "QT5CORE.DLL" called.
DllMain(0x0000000059B90000, DLL_PROCESS_ATTACH, 0x000000000028F4D0) in "QT5CORE.DLL" returned 1 (0x1).
DllMain(0x000007FEE38B0000, DLL_PROCESS_ATTACH, 0x000000000028F4D0) in "ZLIB.DLL" called.
DllMain(0x000007FEE38B0000, DLL_PROCESS_ATTACH, 0x000000000028F4D0) in "ZLIB.DLL" returned 1 (0x1).
DllMain(0x000007FEE3890000, DLL_PROCESS_ATTACH, 0x000000000028F4D0) in "SZIP.DLL" called.
DllMain(0x000007FEE3890000, DLL_PROCESS_ATTACH, 0x000000000028F4D0) in "SZIP.DLL" returned 1 (0x1).
DllMain(0x000007FEE38D0000, DLL_PROCESS_ATTACH, 0x000000000028F4D0) in "HDF5.DLL" called.
DllMain(0x000007FEE38D0000, DLL_PROCESS_ATTACH, 0x000000000028F4D0) in "HDF5.DLL" returned 1 (0x1).
DllMain(0x000007FEE2140000, DLL_PROCESS_ATTACH, 0x000000000028F4D0) in "CGNSDLL.DLL" called.
DllMain(0x000007FEE2140000, DLL_PROCESS_ATTACH, 0x000000000028F4D0) in "CGNSDLL.DLL" returned 1 (0x1).
DllMain(0x000007FEE3850000, DLL_PROCESS_ATTACH, 0x000000000028F4D0) in "IRICLIB.DLL" called.
DllMain(0x000007FEE3850000, DLL_PROCESS_ATTACH, 0x000000000028F4D0) in "IRICLIB.DLL" returned 1 (0x1).
First chance exception 0xC0000005 (Access Violation) occurred in "IRIC_DIR.EXE" at address 0x000000013F9C410B.
Second chance exception 0xC0000005 (Access Violation) occurred in "IRIC_DIR.EXE" at address 0x000000013F9C410B.
Exited "IRIC_DIR.EXE" (process 0x147C) with code 62097 (0xF291).
```

Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for reporting this.

I think I did not changes to iRICLIB.
Anyway, I’ll try to reproduce the issue on my PC.

I have schedules on Monday, and I think I can work on this on Tuesday.

Thanks,

Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

It seems that the iric_acc.exe, iric_dir.exe I've attached had problems.
I've rebuilt, and attach again. Please try with these files again.

Thanks,

[testdata_20180115.zip](https://github.com/i-RIC/prepost-gui/files/1630706/testdata_20180115.zip)

Keisuke

**Pull request merged**
