### PR TITLE
Closes i-RIC/prepost-gui#48

### PR DESCRIPTION
**Pull request by kskinoue0612**

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

When running qmake I'm getting:

```
C:\prepost-gui-PR>qmake -recursive -tp vc
Reading C:/prepost-gui-PR/libs/libs.pro
 Reading C:/prepost-gui-PR/libs/tmsloader/tmsloader.pro
 Reading C:/prepost-gui-PR/libs/cs/cs.pro
 Reading C:/prepost-gui-PR/libs/geoio/geoio.pro
 Reading C:/prepost-gui-PR/libs/misc/misc.pro
 Reading C:/prepost-gui-PR/libs/triangle/triangle.pro
 Reading C:/prepost-gui-PR/libs/guibase/guibase.pro
WARNING: Failure to find: vtkCustomScalarBarActorInternal.h
WARNING: Failure to find: vtkCustomScalarBarActorInternal.h
 Reading C:/prepost-gui-PR/libs/guicore/guicore.pro
 Reading C:/prepost-gui-PR/libs/dataitem/dataitem.pro
  Reading C:/prepost-gui-PR/libs/dataitem/axis2d/axis2d.pro
  Reading C:/prepost-gui-PR/libs/dataitem/axis3d/axis3d.pro
  Reading C:/prepost-gui-PR/libs/dataitem/distancemeasure/distancemeasure.pro
  Reading C:/prepost-gui-PR/libs/dataitem/measureddata/measureddata.pro
...
```

I think you just need to rename

`libs/guibase/vtkScalarBarActorInternal.h`
to
`libs/guibase/vtkCustomScalarBarActorInternal.h`
and update
`libs/guibase/vtkCustomScalarBarActor.cxx`

or

change `vtkCustomScalarBarActorInternal.h` to `vtkScalarBarActorInternal.h`
in `libs/guibase/guibase.pro`

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

I'm sorry for this.
I fixed in the second way that you proposed.

Thanks,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I submitted a pull request to your issue-48 branch.

All it does is add the following to vtkCustomScalarBarActor.cxx:

```
#if (VTK_MAJOR_VERSION != 6) || (VTK_MINOR_VERSION != 1) || (VTK_BUILD_VERSION != 0)
#error May need to update local vtkScalarBarActorInternal.h
#endif
```
This makes sure that if we ever change VTK versions that we resync the local vtkScalarBarActorInternal.h
with the vtk version.  I think the way VTK implemented vtkScalarBarActorInternal is bad since it adds
a dependency on FTGL.h which isn't installed to the include directory. This poor design makes it so that
you can't properly subclass vtkScalarBarActor even though it contains virtual functions.

I once had two header files that got out of sync and it was one of the worst bugs to find and fix.

You can go ahead and merge this yourself once you accept my pull request.

Thanks,

Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you very much for your pull request!
I've merged your pull request, and merged this by myself.

Keisuke

**Pull request merged**
