### PR TITLE
two dimensional cellcenter working

### PR DESCRIPTION
**Pull request by scharlton2**
Hi Keisuke,

Please check what I have done so far.  It should work for two dimensional vertex/cellcenter scalars.  If it's OK, I'll do the same for the one-D and three-D scalars.

Here are links from #205:

Structured Grid:
[Braid-Cell-8.zip](https://github.com/i-RIC/prepost-gui/files/1448670/Braid-Cell-8.zip)

Unstructured Grid:
[CellCenterProject.8.zip](https://github.com/i-RIC/prepost-gui/files/1697498/CellCenterProject.8.zip)

Thanks,
Scott

### CODE REVIEW

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for reporting your progress!

I think I can review your code tonight. I’ll contact you again.

Thanks,

Keisuke


2018年3月3日(土) 12:03 Scott Charlton <notifications@github.com>:

**Comment by kskinoue0612** [comment]
Hi Scott,

I've reviewed your code. It looks quite clean. Thanks for this.

But this is weekend in Japan, so I can not build your branch and test it.
I feel that I should build and test before I say OK, to avoid that I find issues after you finish 1D and 3D functions. I think I can review on next Monday. Please wait for a while.

Thanks,

Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

Hello.
Today I've build your branch and tested. I found no issue.
Please go on with 1D and 3D functions.

Thanks,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I have implemented the 1D and 3D ComboBoxes.  Please let me know what you want me to work on next.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you very much.
I've sent a pull request to your issue-224 branch, to update Japanese translation dictionary.
Please merge that pull request first, and then merge this by yourself.

Talking about what to work on next, I'll have a talk with Kazutake, and contact you again.

Thanks,
Keisuke

**Pull request merged**
