### PR TITLE
Close i-RIC/prepost-gui#513

### PR DESCRIPTION
**Pull request by kskinoue0612**

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

Looks like you forgot to add some files:

```
C:\prepost-gui>qmake -recursive -tp vc
Reading C:/prepost-gui/libs/libs.pro
 Reading C:/prepost-gui/libs/tmsloader/tmsloader.pro
 Reading C:/prepost-gui/libs/cs/cs.pro
 Reading C:/prepost-gui/libs/geoio/geoio.pro
 Reading C:/prepost-gui/libs/misc/misc.pro
WARNING: Failure to find: anms.cpp
WARNING: Failure to find: anms.h
WARNING: Failure to find: dvector.h
WARNING: Failure to find: anms.cpp
WARNING: Failure to find: anms.h
WARNING: Failure to find: dvector.h
 Reading C:/prepost-gui/libs/triangle/triangle.pro
 Reading C:/prepost-gui/libs/guibase/guibase.pro
 Reading C:/prepost-gui/libs/guicore/guicore.pro
 Reading C:/prepost-gui/libs/dataitem/dataitem.pro
  Reading C:/prepost-gui/libs/dataitem/axis2d/axis2d.pro
  Reading C:/prepost-gui/libs/dataitem/axis3d/axis3d.pro
  Reading C:/prepost-gui/libs/dataitem/distancemeasure/distancemeasure.pro
  Reading C:/prepost-gui/libs/dataitem/measureddata/measureddata.pro
 Reading C:/prepost-gui/libs/geodata/geodata.pro
  Reading C:/prepost-gui/libs/geodata/netcdf/netcdf.pro
  Reading C:/prepost-gui/libs/geodata/pointmap/pointmap.pro
  Reading C:/prepost-gui/libs/geodata/polygon/polygon.pro
  Reading C:/prepost-gui/libs/geodata/polyline/polyline.pro
  Reading C:/prepost-gui/libs/geodata/riversurvey/riversurvey.pro
 Reading C:/prepost-gui/libs/gridcreatingcondition/gridcreatingcondition.pro
  Reading C:/prepost-gui/libs/gridcreatingcondition/centerandwidth/centerandwidth.pro
  Reading C:/prepost-gui/libs/gridcreatingcondition/compoundchannel/compoundchannel.pro
  Reading C:/prepost-gui/libs/gridcreatingcondition/externalprogram/externalprogram.pro
  Reading C:/prepost-gui/libs/gridcreatingcondition/gridcombine/gridcombine.pro
  Reading C:/prepost-gui/libs/gridcreatingcondition/gridgenerator/gridgenerator.pro
  Reading C:/prepost-gui/libs/gridcreatingcondition/laplace/laplace.pro
WARNING: Failure to find: gridcreatingconditionlaplacesubregiondeploysettingdialog.cpp
WARNING: Failure to find: private\gridcreatingconditionlaplace_buildsubgridpointsthread.cpp
WARNING: Failure to find: private\gridcreatingconditionlaplace_commonratiooptimizethread.cpp
WARNING: Failure to find: private\gridcreatingconditionlaplace_subregiondeploysettingcommand.cpp
WARNING: Failure to find: gridcreatingconditionlaplacesubregiondeploysettingdialog.h
WARNING: Failure to find: private\gridcreatingconditionlaplace_buildsubgridpointsthread.h
WARNING: Failure to find: private\gridcreatingconditionlaplace_commonratiooptimizethread.h
WARNING: Failure to find: private\gridcreatingconditionlaplace_subregiondeploysettingcommand.h
WARNING: Failure to find: gridcreatingconditionlaplacesubregiondeploysettingdialog.ui
WARNING: Failure to find: gridcreatingconditionlaplacesubregiondeploysettingdialog.cpp
WARNING: Failure to find: private\gridcreatingconditionlaplace_buildsubgridpointsthread.cpp
WARNING: Failure to find: private\gridcreatingconditionlaplace_commonratiooptimizethread.cpp
WARNING: Failure to find: private\gridcreatingconditionlaplace_subregiondeploysettingcommand.cpp
WARNING: Failure to find: gridcreatingconditionlaplacesubregiondeploysettingdialog.h
WARNING: Failure to find: private\gridcreatingconditionlaplace_buildsubgridpointsthread.h
WARNING: Failure to find: private\gridcreatingconditionlaplace_commonratiooptimizethread.h
WARNING: Failure to find: private\gridcreatingconditionlaplace_subregiondeploysettingcommand.h
WARNING: Failure to find: gridcreatingconditionlaplacesubregiondeploysettingdialog.ui
  Reading C:/prepost-gui/libs/gridcreatingcondition/poisson/poisson.pro
  Reading C:/prepost-gui/libs/gridcreatingcondition/rectangularregion/rectangularregion.pro
  Reading C:/prepost-gui/libs/gridcreatingcondition/rectangularregionlonlat/rectangularregionlonlat.pro
  Reading C:/prepost-gui/libs/gridcreatingcondition/riversurvey/riversurvey.pro
  Reading C:/prepost-gui/libs/gridcreatingcondition/riversurvey15d/riversurvey15d.pro
  Reading C:/prepost-gui/libs/gridcreatingcondition/triangle/triangle.pro
 Reading C:/prepost-gui/libs/hydraulicdata/hydraulicdata.pro
  Reading C:/prepost-gui/libs/hydraulicdata/riversurveywaterelevation/riversurveywaterelevation.pro
 Reading C:/prepost-gui/libs/solverconsole/solverconsole.pro
 Reading C:/prepost-gui/libs/postbase/postbase.pro
 Reading C:/prepost-gui/libs/post/post.pro
  Reading C:/prepost-gui/libs/post/post2d/post2d.pro
  Reading C:/prepost-gui/libs/post/post2dbirdeye/post2dbirdeye.pro
  Reading C:/prepost-gui/libs/post/post3d/post3d.pro
  Reading C:/prepost-gui/libs/post/graph2d/graph2d.pro
  Reading C:/prepost-gui/libs/post/graph2dhybrid/graph2dhybrid.pro
  Reading C:/prepost-gui/libs/post/graph2dscattered/graph2dscattered.pro
 Reading C:/prepost-gui/libs/pre/pre.pro
 Reading C:/prepost-gui/libs/gui/gui.pro
 Reading C:/prepost-gui/libs/iricpython/iricpython.pro
Reading C:/prepost-gui/apps/apps.pro
 Reading C:/prepost-gui/apps/rivmaker/rivmaker.pro
 Reading C:/prepost-gui/apps/iricgui/iricgui.pro
Reading C:/prepost-gui/plugins/plugins.pro
 Reading C:/prepost-gui/plugins/gridexporter/gridexporter.pro
  Reading C:/prepost-gui/plugins/gridexporter/structured2dgridnayscsvexporter/structured2dgridnayscsvexporter.pro
  Reading C:/prepost-gui/plugins/gridexporter/structured2dgridnaysgridexporter/structured2dgridnaysgridexporter.pro
  Reading C:/prepost-gui/plugins/gridexporter/structured2dgridvtkexporter/structured2dgridvtkexporter.pro
  Reading C:/prepost-gui/plugins/gridexporter/unstructured2dgridvtkexporter/unstructured2dgridvtkexporter.pro
 Reading C:/prepost-gui/plugins/gridimporter/gridimporter.pro
  Reading C:/prepost-gui/plugins/gridimporter/structured2dgridnayscsvimporter/structured2dgridnayscsvimporter.pro
  Reading C:/prepost-gui/plugins/gridimporter/structured2dgridnaysgridimporter/structured2dgridnaysgridimporter.pro
  Reading C:/prepost-gui/plugins/gridimporter/unstructured2dgridtriangleimporter/unstructured2dgridtriangleimporter.pro
Reading C:/prepost-gui/tests/tests.pro
 Reading C:/prepost-gui/tests/geometry/geometry.pro
 Reading C:/prepost-gui/tests/iricpython/iricpython.pro
```

Thanks
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your contact, and I'm sorry for this.
I will check and fix this later today.

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I've made sure that now building succeeds.
Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I noticed that if you skip 'Build left bank and right bank lines' step that iRIC crashes:

image
image
image
image
image
image

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your information.

I'm going to fix and push another commit.
Now I'm working on CAP issue with higher priority, and maybe I can work on this on tomorrow or on Friday.

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I've pushed a commit to fix the issue that you've reported.

Thanks,
Keisuke

**Pull request merged**
