### PR TITLE
Closes i-RIC/prepost-gui#308

### PR DESCRIPTION
**Pull request by kskinoue0612**

### CODE REVIEW

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for merging pull requests.
It seems that this pull request has a conflict with master branch now, so I'll resolve the conflict and push a commit later.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

OK.  I was trying different merge strategies but I had a hard time comparing the differences. (see https://git-scm.com/docs/merge-strategies).  I also looked at (https://stackoverflow.com/questions/28220472/best-practice-for-qt-translations-and-git).  If you have some trick that you use to merge *.ts files let me know.

Thanks,
Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

Since #321 contains changes to *.ts files, I'll wait until this one is done before merging #321.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

I've rebased issue-308 onto master, and run lupdate.exe, lrelease.exe. I had to edit *.ts file to resolve collisions.

I know it is not a very clever way, but was simple and easy for me.

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

> Since #321 contains changes to *.ts files, I'll wait until this one is done before merging #321.
> 
> Thanks,
> Scott

I've rebased both issue-308 and issue-307 branches onto master. It seems that they can be merged without conflicts.

Thanks,
Keisuke

**Pull request merged**
