### PR TITLE
Closes #784

### LINKED ISSUE #784: Add tool to remove <location/> element from *.ts
In internationalization dictionaries (languages/*.ts), messages are stored in code like below:

```
<context>
    <name>DBFItemSelectDialog</name>
    <message>
        <location filename="../private/dbfitemselectdialog.ui" line="14"/>
        <source>Dialog</source>
        <translation type="unfinished"></translation>
    </message>
</context>
```

For developers, information in `<location />` element is helpful, because thanks to this information, we can see the corresponding source code on Qt Linguist.

But, `<location />` element cause a big issue. It often cause collisions between branches. The reason is that when we update the source code, the messages themselves are the same, but the line number often changes. This makes it difficult to merge pull requests.

To avoid this issue, develop a simple tool to remove `<location />` element from *.ts. When `<location />` element is removed, *.ts will be updated only when we've added or modified messages. And, if we want to restore `<location />` tag, we can do it easily, by running lupdate.exe.

After running the tool, the code above will be like below:

```
<context>
    <name>DBFItemSelectDialog</name>
    <message>
        <source>Dialog</source>
        <translation type="unfinished"></translation>
    </message>
</context>
```

### PR DESCRIPTION
**Pull request by kskinoue0612**

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

I'm not sure how I'm supposed to use this.

Is it:

1. Add a translatable string in a .cpp file:
  QAction* nt= menu->addAction(tr("New translation string"));

2. cd prepost-gui

3. lupdate src.pro

4. cd tools

5. python i18ntool.py build

6. git commit -am "Updated dictionaries"

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for the comment.
Yes, that's the way we are going to use the tool. If we keep using the tool, we'll have less collisions because of changes to `<location />` element.

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,
I've rebased the branch to the develop branch to resolve the conflict, so that you can merge this pull request by yourself.
I've added no modifications to the commits.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

When I ran:

`python i18ntool.py build`

and then checked for diffs:

```
> git diff
diff --git a/languages/iRIC_es_ES.ts b/languages/iRIC_es_ES.ts
index b4fa7226..dc04c422 100644
--- a/languages/iRIC_es_ES.ts
+++ b/languages/iRIC_es_ES.ts
@@ -3756,6 +3756,7 @@ p, li { white-space: pre-wrap; }
         <source>Custom Color</source>
         <translation type="unfinished"></translation>
     </message>
+    <message>
         <source>polygon</source>
         <translation type="unfinished"></translation>
     </message>
diff --git a/languages/iricGdPolygonGroup_es_ES.ts b/languages/iricGdPolygonGroup_es_ES.ts
index 5af06349..a900afce 100644
--- a/languages/iricGdPolygonGroup_es_ES.ts
+++ b/languages/iricGdPolygonGroup_es_ES.ts
@@ -148,6 +148,7 @@
         <source>Custom Color</source>
         <translation type="unfinished"></translation>
     </message>
+    <message>
         <source>polygon</source>
         <translation type="unfinished"></translation>
     </message>
```

Do you know why the beginning message element for polygon keeps getting added and removed?  It looks like you fixed it in https://github.com/i-RIC/prepost-gui/pull/785/commits/6cbe38f20aa3d9bd349f52b1826c79b9f25139e2 once already.  Maybe message is on the same line as the location element?

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for the notification.
I'm sorry that it took time, I've checked, and identified the reason.

In 6cbe38f, I've noticed the problem and fixed the dictionary file libs/geodata/polygongroup/languages/iricGdPolygonGroup_es_ES.ts. But I did not run `python i18ntool.py build`.

`python i18ntool.py build` command do the followings now:

1. Remove `<location />` element
2. Copy dictionary files from libs/xxxxx/languages folder to languages folder, so that translators can easily find the dictionaries.
3. Merge dictionary files for each DLLs into one dictionary for each language. ex. languages/xxxxxx_es_ES.ts into languages/iRIC_es_ES.ts.

The steps 2. and 3. caused the diff you've noticed.

Now I've pushed another commit 5613900. I've checked that when I run `python i18ntool.py build`, no diff appears again.

Thanks,

Keisuke

**Pull request merged**
