### PR TITLE
Closes i-RIC/prepost#205

### PR DESCRIPTION
**Pull request by scharlton2**
Closes Issue: https://github.com/i-RIC/prepost-gui/issues/205

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

Please do not test this yet.  I found that it doesn't work with unstructured grids.  I'll let you know when its ready to test again.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

I’ve got it. Thanks for informing.

Keisuke
> Hi Keisuke,
> 
> Please do not test this yet. I found that it doesn't work with unstructured grids. I'll let you know when its ready to test again.
> 
> Thanks,
> Scott
>

**Comment by scharlton2** [comment]
Hi Keisuke,

I noticed that I'm getting slightly different results for cell-centered color fringe contours between post2d and post2dbirdeye windows:

braid-cell-8-2

I originally thought that it was due to differing Lookup Tables but I dumped the m_fringeMapper of each and didn't see anything different:

#### Post2d m_fringeMapper (Post2dWindowCellScalarGroupDataItem):
```
 Debug: Off
Modified Time: 1497723
Reference Count: 3
Registered Events: (none)
Executive: 0000000050C00B40
ErrorCode: No error
Information: 0000000053248320
AbortExecute: Off
Progress: 1
Progress Text: (None)
TimeToDraw: 0.00600004
ClippingPlanes: (none)
Lookup Table:
  Debug: Off
  Modified Time: 1497723
  Reference Count: 8
  Registered Events: (none)
  Alpha: 1
  VectorMode: Component
  VectorComponent: 0
  VectorSize: -1
  IndexedLookup: OFF
  AnnotatedValues: 0 entries.
  Size: 2
  Clamping: On
  Color Space: HSV (No Wrap)
  Scale: Linear
  Range: 0 to 4.49205
  AllowDuplicateScalars: 0
  NanColor: 0.5, 0, 0
    0 X: 0 R: 2e-005 G: 0 B: 1 Sharpness: 0 Midpoint: 0.5
    1 X: 4.49205 R: 1 G: 0 B: 0 Sharpness: 0 Midpoint: 0.5
Immediate Mode Rendering: Off
Force compile only for display lists: Off
Global Immediate Mode Rendering: Off
Scalar Visibility: On
Static: Off
Scalar Range: (0, 1)
UseLookupTableScalarRange: 1
Color Mode: Default
InterpolateScalarsBeforeMapping: Off
Scalar Mode: UseCellFieldData
LM Color Mode: Default
RenderTime: 0
Resolve Coincident Topology: Off
Poly Mapper: (0000000053FADBF0)
Geometry Extractor: (0000000053FAC2C0)
```

#### Post2dBridEye m_fringeMapper (Post2dBirdEyeWindowCellScalarGroupDataItem):
```
 Debug: Off
Modified Time: 1035739
Reference Count: 3
Registered Events: (none)
Executive: 0000000053AD8180
ErrorCode: No error
Information: 0000000053993460
AbortExecute: Off
Progress: 1
Progress Text: (None)
TimeToDraw: 0.00700021
ClippingPlanes: (none)
Lookup Table:
  Debug: Off
  Modified Time: 1035739
  Reference Count: 8
  Registered Events: (none)
  Alpha: 1
  VectorMode: Component
  VectorComponent: 0
  VectorSize: -1
  IndexedLookup: OFF
  AnnotatedValues: 0 entries.
  Size: 2
  Clamping: On
  Color Space: HSV (No Wrap)
  Scale: Linear
  Range: 0 to 4.49205
  AllowDuplicateScalars: 0
  NanColor: 0.5, 0, 0
    0 X: 0 R: 2e-005 G: 0 B: 1 Sharpness: 0 Midpoint: 0.5
    1 X: 4.49205 R: 1 G: 0 B: 0 Sharpness: 0 Midpoint: 0.5
Immediate Mode Rendering: Off
Force compile only for display lists: Off
Global Immediate Mode Rendering: Off
Scalar Visibility: On
Static: Off
Scalar Range: (0, 1)
UseLookupTableScalarRange: 1
Color Mode: Default
InterpolateScalarsBeforeMapping: Off
Scalar Mode: UseCellFieldData
LM Color Mode: Default
RenderTime: 0
Resolve Coincident Topology: Off
Poly Mapper: (0000000053A56BC0)
Geometry Extractor: (0000000053A55290)
```

Do you have any ideas that might cause this difference?

Based on my issue-205 branch (commit 718e3a5080b5a58b385582efbe4ed162deecefc2) and 
using [Braid-Cell-8.zip](https://github.com/i-RIC/prepost-gui/files/1448670/Braid-Cell-8.zip) as input.

Thanks,
Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

After looking at this with Rich we were able to determine that the difference is due to the camera/lighting angles.   By rotating the Bird's-Eye view about the x-axis additional detail can be seen:

braid-cell-8-3

Thanks,
Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

It turns out the difference is due to the SetLighting settings:

[libs/post/post2d/datamodel/post2dwindowcellscalargroupdataitem.cpp:222](https://github.com/i-RIC/prepost-gui/blob/718e3a5080b5a58b385582efbe4ed162deecefc2/libs/post/post2d/datamodel/post2dwindowcellscalargroupdataitem.cpp#L222)
```
	m_fringeActor->GetProperty()->SetLighting(false);
```
vs

[libs/post/post2dbirdeye/datamodel/post2dbirdeyewindowcellscalargroupdataitem.cpp:170](https://github.com/i-RIC/prepost-gui/blob/718e3a5080b5a58b385582efbe4ed162deecefc2/libs/post/post2dbirdeye/datamodel/post2dbirdeyewindowcellscalargroupdataitem.cpp#L170)
```
	m_fringeActor->GetProperty()->SetLighting(true);
```

Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your comments. Glad that the issue is solved.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

During the shutdown, the project I worked for previous to Jonathan's lost a subversion repository.  I spent most of today recovering and moving it to another machine (once we found the machine).  

I was able to determine that the problem I'm having with the unstructured grid (Bird's eye) was due to there not being an elevation for the `vtkWarpScalar` object to process.  How do you want to handle this case?  Do you want to bypass the `vtkWarpScalar` when `PostZoneDataContainer::elevationName()` returns an empty string?  Let me know if you have any other ideas.

I'm feeling pretty sick right now so I'll probably not be in the rest of the week.

Hope all is well with you,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for the comment, and I hope you’ll get well soon. I’m OK now, but today we’ve got a snow in Tokyo today. I’ll take care not to catch a cold.

I’m not sure, but does the solver output elevation with other name than “elevation”? If so, I think it is not a issue of iRIC GUI, and we can ask the solver developer to output with name “elevation”.

I hope I’m not missing the point.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Yes, you are right, I renamed "Bed Elevation" to "Elevation".  Here are some files to test the Post2dBirdEye items.

Structured Grid:
[Braid-Cell-8.zip](https://github.com/i-RIC/prepost-gui/files/1448670/Braid-Cell-8.zip)

And here's a file to test the unstructured grid (its CellCenterProject.4 with "Bed Elevation" renamed to "Elevation":
[CellCenterProject.8.zip](https://github.com/i-RIC/prepost-gui/files/1697498/CellCenterProject.8.zip)

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

I've tested your code, and it worked fine. Thanks for this.

I've sent a pull request to your issue-205 branch, to update Japanese translation dictionary files.
Please merge that pull request first, and merge this by yourself.

Thanks,
Keisuke

**Pull request merged**
