### PR TITLE
Close #457, Close #853

### LINKED ISSUE #457: Enhance arrow setting on post3d window so that we can change colors of arrows for each faces
Currently, the color setting of arrows on post3d window is applied to all faces. We enhance the function so that user can specify colors for each face individually.

Below is the dialog implemented currently.

screenshot_1

We modify the dialog layout to below, to enhance the function.

screenshot_2

### LINKED ISSUE #853: Add function to set sampling rate for I, J, K direction individually in post3d arrow setting dialog
In 2D visualization window, arrow setting dialog looks like below. We can edit sampling rate individually for i-direction and j-direction.

2d_dialog

But in 3d visualization window, we can input only one sampling rate value. Because of this, in 3d visualization window, it happens that arrows are shown in diagonal positions, like shown below.

It is not convenient.

Improve the post3d arrow setting dialog, so that we can edit sampling rate for I, J, K direction individually, like in 2d window.

### PR DESCRIPTION
**Pull request by kskinoue0612**
Please try with the steps below:

1. Launch iRIC
2. Select Import -> Calculation Result menu, and import 3dtest.cgn
3. Open Post3D window
4. Select "Arrows", and select "Add" from right-clicking menu
5. Make sure that "Sampling", Color", "Arrow Shape" are now moved to "Faces" group box, and not it is possible to specify different values for each face.

[issue-457-853.zip](https://github.com/i-RIC/prepost-gui/files/6263854/issue-457-853.zip)

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

When the 'By scalar value' is selected for 'Color', the dropdown list is not updated when the dialog is reopened:

image

image

image

image

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for testing, and reporting the issue. I'm going to fix it.
It seems that collision exists on Post3d window dictionaries, so When I've fixed, I'll  rebase the branch to develop, and push with -f option.

Thank you,

Keisuke Inoue

**Comment by kskinoue0612** [comment]
Hi Scott,

I've fixed the bug, and rebased the branch to develop, to resolve collisions.
Thank you,

Keisuke Inoue

**Comment by scharlton2** [comment]
Hi Keisueke,

I fixed a few things:

1e33944 - Arrows child caption not updated after reopening:

image
image

9f8fe41 - Face enable not synchronized:

image
image
image


If you're okay with my changes, you can finish the merge.

Thanks,
Scott

**Pull request merged**
