### PR TITLE
Breakline intersection

### PR DESCRIPTION
**Pull request by Leon-Zhang**
unionLines function added.

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Leon,

For this branch (breakline_intersection) you need to re-add the geos library back into:
`libs/gridcreatingcondition/triangle/triangle.pro`

**Comment by Leon-Zhang** [comment]
Hi Scott,

Thanks for the check. 

Pro file lib reference added.

And I have added missed delete also, please check.

But for GeometryFactory's create function, seems it doesn't need to be destroyed.

Thanks,
Leon

**Comment by scharlton2** [comment]
Hi Leon,

If you step into:

    geos::geom::CoordinateSequence* csLRing = csFactory->create(&coordsLRing);

You'll see that its implemented:

```
INLINE CoordinateSequence *
CoordinateArraySequenceFactory::create(std::vector<Coordinate> *coords,
		size_t dimension ) const
{
	return new CoordinateArraySequence(coords,dimension);
}
```
in the file:

    <iricdev>\lib\src\geos-3.4.3\include\geos\geom\CoordinateArraySequenceFactory.inl

So, I think it needs to be deleted.  Sorry, but I don't have time to look at it carefully.  Looking at the documentation, it looks like some things ARE garbage collected.  Tomorrow, I'll create a small test
and run it through Valgrind or something similar.

Scott

**Comment by kskinoue0612** [comment]
Scott, thank you for your comment.

Leon, I think you need to know some more about how to use geos library.
I've created a small test program that represents how geos::geom::GeometryCollection::Union() works, in the following branch.

https://github.com/kskinoue0612/prepost-gui/commits/test_geos_lineunion

Reviewing the main.cpp there, you'll know how to use geos library classes.

The program bundles three test cases. You can see how the input lines looks like by opening PNG files.
and, running the test, you'll get test1_output.csv, test1_output.vtk etc. that contains the result of unioning lines. You'll see that points are added at cross-section points correctly.

**Comment by kskinoue0612** [comment]
I close this pull request, because #158 will be the alternative to this pull request.

**Pull request closed without merging**
