### PR TITLE
Add polygons contain judgement.

### PR DESCRIPTION
**Pull request by Leon-Zhang**
Polygon intersection judgement fix.

### CODE REVIEW

**Comment by scharlton2** [comment]
I'm not sure what you're are trying to test in PolygonContain.  I think you
are trying to see if any polygons share a vertex.  If this is the case I 
would implement it like this:

	bool sharesVertex(const QPolygonF& l, const QPolygonF& r)
	{
		for (int i = 0; i < r.length();i++) {
			QPointF pt = r.at(i);
			if (l.contains(r.at(i))) {
				return true;
			}
		}
		return false;
	}

Also the logic for you checkPlygonsIntersection isn't quite right. The
if statement should be OR (||) instead of AND (&&):

	if (!pol1.intersected(pol2).isEmpty() || !PolygonContain(pol1, pol2)) {

and I would implement it this way:

	// static
	// returns true if any polygons intersect
	bool GridCreatingConditionTriangle::checkPolygonsIntersection(const QList<QPolygonF>& polygons)
	{
		for (int i = 0; i < polygons.count(); ++i) {
			for (int j = i + 1; j < polygons.count(); ++j) {
				QPolygonF pol1 = polygons[i];
				QPolygonF pol2 = polygons[j];

				if (!pol1.intersected(pol2).isEmpty() || sharesVertex(pol1, pol2)) {
					// intersects!
					return true;
				}
			}
		}
		return false;
	}

I've changed it to return true if there are any intersections and false otherwise
but this is just a personal preference.

And would also require the following change:

	if (checkPolygonsIntersection(polygons)) {
		QMessageBox::warning(preProcessorWindow(), tr("Warning"), tr("Remesh polygons and hole polygons can not have intersections."));
		return false;
	}

Here are some unit tests.  I've commented out the asserts that are not working.  I'm
not sure if Case 3 and Case 6 are necessary for iRIC's implementation.  If so, you'll
need to have a look at http://www.faqs.org/faqs/graphics/algorithms-faq/ section
1.03 for the case that both the numerator and denominator are zero (collinear).

The Qt function:

	QLineF::IntersectType QLineF::intersect(const QLineF &l, QPointF *intersectionPoint) const

pretty much uses section 1.03 except it ignores the case where both denominator
and numerator equal zero.

	{
		// Case 1
		// two non-intersecting polygons
		//      x=0   x=2    x=4   x=6
		//       
		//       1     2      4     5
		// y=1   *     *      *     *
		// 
		// y=0      *            *
		//          3            6

		QPolygonF poly1;
		poly1.append(QPoint(0.0, 1.0));  // 1
		poly1.append(QPoint(2.0, 1.0));  // 2
		poly1.append(QPoint(1.0, 0.0));  // 3
		poly1.append(QPoint(0.0, 1.0));  // 1
		assert(poly1.isClosed());

		QPolygonF poly2;
		poly2.append(QPoint(4.0, 1.0));  // 4
		poly2.append(QPoint(6.0, 1.0));  // 5
		poly2.append(QPoint(5.0, 0.0));  // 6 
		poly2.append(QPoint(4.0, 1.0));  // 4
		assert(poly2.isClosed());
		assert(!sharesVertex(poly1, poly2));

		QList<QPolygonF> polys;
		polys.append(poly1);
		polys.append(poly2);
		assert(checkPolygonsIntersection(polys) == false);
	}

	{
		// Case 2
		// two polygons that share a vertex
		//      x=0   x=2   x=4
		//       
		//       1     2     4
		// y=1   *     *     *
		// 
		// y=0      *     *
		//          3     5

		QPolygonF poly1;  // 1-2-3
		poly1.append(QPoint(0.0, 1.0));  // 1
		poly1.append(QPoint(2.0, 1.0));  // 2
		poly1.append(QPoint(1.0, 0.0));  // 3
		poly1.append(QPoint(0.0, 1.0));  // 1
		assert(poly1.isClosed());

		QPolygonF poly2;  // 2-4-5
		poly2.append(QPoint(2.0, 1.0));  // 2
		poly2.append(QPoint(4.0, 1.0));  // 4
		poly2.append(QPoint(3.0, 0.0));  // 5 
		poly2.append(QPoint(2.0, 1.0));  // 2
		assert(poly2.isClosed());
		assert(sharesVertex(poly1, poly2));
	}

	{
		// Case 3
		// two polygons that overlap sides
		//      x=0   x=2   x=4   x=6
		//       
		//                5
		// y=2            *
		//       
		//       1     4     6     2
		// y=1   *     *     *     *
		//       
		//       
		// y=0            *
		//                3

		QPolygonF poly1;   // 1-2-3
		poly1.append(QPoint(0.0, 1.0));  // 1
		poly1.append(QPoint(6.0, 1.0));  // 2
		poly1.append(QPoint(3.0, 0.0));  // 3
		poly1.append(QPoint(0.0, 1.0));  // 1
		assert(poly1.isClosed());

		QPolygonF poly2;   // 4-5-6
		poly2.append(QPoint(2.0, 1.0));  // 4
		poly2.append(QPoint(3.0, 2.0));  // 5
		poly2.append(QPoint(4.0, 1.0));  // 6
		poly2.append(QPoint(2.0, 1.0));  // 4
		assert(poly2.isClosed());
		assert(!sharesVertex(poly1, poly2));


		QList<QPolygonF> polys;
		polys.append(poly1);
		polys.append(poly2);
		// assert(checkPolygonsIntersection(polys) == true);  this fails
	}

	{
		// Case 4
		// two polygons that overlap
		//      x=0      x=1      x=2
		//       1                 2
		// y=3   *                 *          
		//
		//                5
		// y=2            *
		//                 
		//                 
		// y=1            *
		//                3
		//
		// y=0   *                 *
		//       4                 6
		QPolygonF poly1;   // 1-2-3
		poly1.append(QPoint(0.0, 3.0));  // 1
		poly1.append(QPoint(2.0, 3.0));  // 2
		poly1.append(QPoint(1.0, 1.0));  // 3
		poly1.append(QPoint(0.0, 3.0));  // 1
		assert(poly1.isClosed());

		QPolygonF poly2;   // 4-5-6
		poly2.append(QPoint(0.0, 0.0));  // 4
		poly2.append(QPoint(1.0, 2.0));  // 5
		poly2.append(QPoint(2.0, 0.0));  // 6
		poly2.append(QPoint(0.0, 0.0));  // 4
		assert(poly2.isClosed());
		assert(!sharesVertex(poly1, poly2));

		QList<QPolygonF> polys;
		polys.append(poly1);
		polys.append(poly2);
		assert(checkPolygonsIntersection(polys) == true);
	}

	{
		// Case 5
		// self intersecting polygon
		//      x=0      x=1
		//       1        2
		// y=1   *        *          
		//
		//
		// y=0   *        *
		//       3        4
		QPolygonF selfIntersects;   // 1-2-3-4
		selfIntersects.append(QPoint(0.0, 1.0));  // 1
		selfIntersects.append(QPoint(1.0, 1.0));  // 2
		selfIntersects.append(QPoint(0.0, 0.0));  // 3
		selfIntersects.append(QPoint(1.0, 0.0));  // 4
		selfIntersects.append(QPoint(0.0, 1.0));  // 1
		assert(selfIntersects.isClosed());
		assert(iRIC::hasIntersection(selfIntersects));
	}


	{
		// Case 6
		// self intersecting polygon (collinear)
		//
		//      x=0   x=1   x=2   x=3
		//       
		//       1     3     2     4
		// y=1   *     *     *     *
		//       
		//       
		// y=0   *
		//       5

		QPolygonF selfIntersects;
		selfIntersects.append(QPoint(0.0, 1.0));  // 1
		selfIntersects.append(QPoint(2.0, 1.0));  // 2
		selfIntersects.append(QPoint(1.0, 1.0));  // 3
		selfIntersects.append(QPoint(3.0, 1.0));  // 4
		selfIntersects.append(QPoint(0.0, 0.0));  // 5
		selfIntersects.append(QPoint(0.0, 1.0));  // 1
		assert(selfIntersects.isClosed());
		// assert(iRIC::hasIntersection(selfIntersects)); this fails
	}

**Comment by Leon-Zhang** [comment]
Hi Scott, thanks for your review.
I have corrected the code little bit for review, please check again.

**Comment by scharlton2** [comment]
Hi Leon,
It's not linking for me.  I think you need to add the geos library to the file:

    libs/gridcreatingcondition/triangle/triangle.pro

You probably added it directly to the iricGccTriangle project.

Also, could you tell me what you're are trying to fix with these changes?  I can tell
that you're adding the ability to "redivide a breakline" but I'm not sure about the tests
you're adding to GridCreatingConditionTriangle::checkCondition.  Are you trying to fix
a specific issue/bug?  If so could you please describe it and/or provide an example
input file?

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for the comment.
And, I'm sorry that I have forgotten to share information about the function that I asked Leon to add.
I've added them as issues, as below:

- https://github.com/i-RIC/prepost-gui/issues/103
- https://github.com/i-RIC/prepost-gui/issues/104

I've also added https://github.com/i-RIC/prepost-gui/issues/105, but this is not included in this pull request.

I'll also will check this pull request, and add comment after checking.

Thanks.

**Comment by scharlton2** [comment]
Hi Keisuke,

Thanks for adding the issues.  By the way, how did you create and add the images?  I wanted
to do this for my original comment.

Thanks

**Comment by Leon-Zhang** [comment]
Hi Scott,

Sorry for the lib problem, I added iricdev_2013\lib\install\geos-3.4.3\release\lib\geos.lib reference
to VS2013 project file, please add this lib reference to your VS project too.
Since VS2013 project file is been generated from pro, so we don't have .vcxproj files in repository.

Regards,

**Comment by scharlton2** [comment]
Hi Leon,

Sorry, I meant that you should make the following change:

    $ git diff libs/gridcreatingcondition/triangle/triangle.pro
    diff --git a/libs/gridcreatingcondition/triangle/triangle.pro b/libs/gridcreatingcondition/triangle/triangle.pro
    index e562edd8..f6e71abc 100644
    --- a/libs/gridcreatingcondition/triangle/triangle.pro
    +++ b/libs/gridcreatingcondition/triangle/triangle.pro
    @@ -78,6 +78,10 @@ LIBS += -liricGuicore
     # External libraries #
     ######################
    
    +# geos
    +
    +LIBS += -lgeos
    +
     # VTK
    
     LIBS += \

and check it in so that we don't have to manually add libraries
and or include paths to visual studio projects.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for the comments to support Leon.

You can upload images to attach to comment, by dragging & dropping to the area that is just below the textarea for the comment. You can also just click the area and select the images to upload.

**Comment by scharlton2** [comment]
Hi Leon,

When I try to generate a grid I'm getting the following assertion:

assert

with the following callstack:


 	msvcp120d.dll!000007fee00465d6()	Unknown
 	geos.dll!std::auto_ptr<geos::geom::Geometry>::operator*() Line 961	C++
 	geos.dll!geos::operation::geounion::UnaryUnionOp::Union() Line 96	C++
 	geos.dll!geos::operation::geounion::UnaryUnionOp::Union(const geos::geom::Geometry & geom) Line 107	C++
 	geos.dll!geos::geom::Geometry::Union() Line 571	C++
 	iricGccTriangle.dll!GridCreatingConditionTriangle::unionLines() Line 1776	C++
 	iricGccTriangle.dll!GridCreatingConditionTriangle::create(QWidget * parent) Line 1755	C++
 	iricPre.dll!PreProcessorGridCreatingConditionDataItem::createGrid() Line 189	C++

Steps to reproduce:

1. Start new project with "Mflow_02 iric ver3 64 bit" solver.
2. Right-click "Grid Creating Condition"->"Import..." and open the following file:
[CellCenterProject.export.igcc.zip](https://github.com/i-RIC/prepost-gui/files/1171448/CellCenterProject.export.igcc.zip)
3. Press the fit toolbar button (7th from the left)
4. Right-click "Grid Creating Condition"->"Create Grid..."->OK

**Comment by scharlton2** [comment]
Hello All,

Sorry, I pressed the "Close pull request" by accident.

Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for reviewing and testing the pull request.
I've also reviewed, and it seems that this pull request contains modifications related to three issues:
- https://github.com/i-RIC/prepost-gui/issues/103 Add function to re-devide breaklines, for unstructured grid generating algorithm enhancement
- https://github.com/i-RIC/prepost-gui/issues/104 Enhance unstructured grid generator, to make it possible to define refinement polygon recursively
- https://github.com/i-RIC/prepost-gui/issues/105 Enhance unstructured grid generator, to make it possible to define breaklines that crosses grid generating region

**Pull request closed without merging**
