### PR TITLE
Closes i-RIC/prepost-gui#223

### PR DESCRIPTION
**Pull request by kskinoue0612**
Hi Scott,

Thanks for reviewing and merging the pull requests.
This is a branch to fix a rather major bug, so I hope we can merge this pull request this week.

I think this will be the last pull request I'll ask you to review this week.

Thanks,
Keisuke

### CODE REVIEW

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your information. The same phenomenon happened on my environment too.
I run in debug mode, and it seems to me that vtkStreamer::ThreadedIntegrate() go into infinite loop.

I'll look into this more, and share information if I get to know something.

Maybe something that I should try is to upgrade VTK. As we've discussed before, I'm going to
try upgrading VTK to 6.3.0.

Talking about VTK_DEBUG_LEAKS, I've never tried before. I'm not sure this issue is related to a memory leak, but anyway it will be helpful to get VTK with VTK_DEBUG_LEAKS option, for debugging.

If you have time, I'll be thankful if you investigate the way to make VTK_DEBUG_LEAKS option ON.

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your work on VTK 6.3.0.

Let me share information about my work in progress.

Now I'm trying to re-implement particle tracking function not using vtkStreamer, but using vtkStreamTracer. The reason that I'm trying to do this is that in the release note of VTK 7.0, it is explained that vtkStreamer class is deprecated and users are encouraged to use vtkStreamTracer instead.

https://blog.kitware.com/vtk-7-0-0/

vtkStreamTracer is not a very new class, and we can use vtkStreamTracer with VTK 6.1.0. If my work get success, maybe we do not have to move to VTK 6.3.0 just to fix this issue. But your work will help anyway, because VTK goes forward so fast, and we'll need to upgrade VTK in the near future anyway.

When I get to have progress enough to show you, I'll share my code and ask you to review.

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I've pushed two commits to fix this issue. As written in commit logs, I've modified the code not to use vtkStreamPoints, but vtkStreamTracer.

It seems me that it is working fine. With the tutorial project you've sent me, the positions of particles are almost the same to the old implementation, and it does not hang up with data at t = 7000s.

The drawback of the new implementation is that now stream integration is not stopped after the deltaT  have passed, but it integrate until the particle goes out of the region. I think I can make improvement for speed up at this point.

Anyway, I've just pushed my code so that you can test. If it seems OK to you, I'll do the improvement above, and make similar modification to 3D post window.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

It seems to be working OK.  I did notice that this version and the previous version's "Step Backwards" clears all the particles from the scene.  Has it always acted this way?  Sorry it took me so long to review, I messed up my build machine working on the VTK_DEBUG_LEAKS version.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for testing my code!

Hi Keisuke,
>
> It seems to be working OK. I did notice that this version and the previous
> version's "Step Backwards" clears all the particles from the scene. Has it
> always acted this way?
>

Yes, it has acted this way. It will not be a problem.

> Sorry it took me so long to review, I messed up my build machine working
> on the VTK_DEBUG_LEAKS version.
>

No problem, it is in the weekend already in Japan :-). I can imagine
working on VTK takes time, because I also built VTK 6.3 and 7.1 recently.

I’ll do some additional works on speed up and post3d window, and contact
you again, maybe on next Monday.

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I've made several commits to do the followings:
* Implement vtkCustomStreamTracer class. Using this, particle tracking can be done faster.
* Use vtkCustomStreamTracer in Post2d window.
* Do the similar modification I've done on post2d window, to post3d window.

For post3d window, I used the following file to test. Please download and run the solver to setup calculation result to test post3d window.

[issue223-cube.zip](https://github.com/i-RIC/prepost-gui/files/2021298/issue223-cube.zip)

I did not succeed to setup a solution with which iRIC post3d window hang up, but with the test data above, I've made sure post3d window particle tracking function works, with higher speed than the old implementation. I think vtkCustomStreamTracer is tested with post2d window, so it will be OK.

Thanks,
Keisuke

**Pull request merged**
