### PR TITLE
Close #801

### LINKED ISSUE #801: When Project for RRI is created, "Reference Information" group is not created in "Geograhic data" group.

### PR DESCRIPTION
**Pull request by kskinoue0612**
Please test with the steps below:
1. copy "RRI" folder to "solvers" folder.
2. Launch iRIC, and start project for solver "Rainfall-Runoff-Inundation v1.4.2"

Without this branch, "Reference Information" group is not displayed. With this branch, that is displayed.

[issue-801.zip](https://github.com/i-RIC/prepost-gui/files/5836017/issue-801.zip)

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,
Everything seems okay, but I found a typo and I tried to fix it by replacing all occurrences in the *.ts files.  I then ran the following:

cd prepost-gui
lupdate.exe .\src.pro
cd tools
python i18ntool.py build

but, it didn't seem to remove the locations.  Here's the diffs for languages/iRIC_es_ES.ts
```
diff --git a/languages/iRIC_es_ES.ts b/languages/iRIC_es_ES.ts
index a68f6724..fbc4a7b9 100644
--- a/languages/iRIC_es_ES.ts
+++ b/languages/iRIC_es_ES.ts
@@ -70,7 +70,7 @@
         <translation type="unfinished"></translation>
     </message>
     <message>
-        <location filename="../coordinatesystemselectdialog.cpp" line="47"/>
+        <location filename="../coordinatesystemselectdialog.cpp" line="56"/>
         <source>(Not Specified)</source>
         <translation>(No Especificado)</translation>
     </message>
@@ -2924,35 +2924,50 @@ p, li { white-space: pre-wrap; }
 <context>
     <name>GeoDataNetcdfGdalImporter</name>
     <message>
-        <location filename="../geodatanetcdfgdalimporter.cpp" line="37"/>
+        <location filename="../geodatanetcdfgdalimporter.cpp" line="45"/>
+        <source>Importing data...</source>
+        <translation type="unfinished"></translation>
+    </message>
+    <message>
+        <location filename="../geodatanetcdfgdalimporter.cpp" line="54"/>
         <source>GDAL</source>
         <translation type="unfinished"></translation>
     </message>
     <message>
-        <location filename="../geodatanetcdfgdalimporter.cpp" line="49"/>
+        <location filename="../geodatanetcdfgdalimporter.cpp" line="66"/>
         <source>GeoTiff files(*.tif)</source>
         <translation type="unfinished"></translation>
     </message>
     <message>
-        <location filename="../geodatanetcdfgdalimporter.cpp" line="50"/>
+        <location filename="../geodatanetcdfgdalimporter.cpp" line="67"/>
         <source>ArcInfo ASCII files(*.asc)</source>
         <translation type="unfinished"></translation>
     </message>
     <message>
:
```

Am I missing a step?

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for your contact.

> Am I missing a step?

No, I do not think so. I've checked i18ntools.py, and made sure that it implements shrinkDictsInSrc(), that removes \<location /\> tags from dictionary files. shrinkDictsInSrc() is called with `python i18ntools.py build`.

I've tried on my environment, and on my PC, \<location /\> tags does not exists after running `python i18ntools.py build`. I'm not sure why the results are different.

Can you push the commits to fix typos please? Then I'll try running lupdate.pro, and i18ntools.py, and share the result.

I've also noticed that i18ntools.py output *.ts with line endings CRLF. It seems that git checkout *.ts files with LF line endings, regardless of core.autoCRLF setting, so I think i18ntools.py should output *.ts with line endings LF. That will make us check diffs easier. What do you think?

Thanks,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I pushed to your github repo.  I just learned about `git checkout .`  Saved me from deleting modified files and checking them back out.  I'm not sure why my commit 3b3adaf was rejected by appveyor.

Thanks,
Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

Now I see why it failed, but I don't understand why there were conflicts.

Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

I looked through i18ntool.py and there was no shrinkDictsInSrc function.  You must have started this branch before making that modification.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for fixing the typo.

Reading the commits you've made, I've done the following steps, to apply the typo fixing to both master and develop branch.

1. On issue-801 branch, made a commit just to fix the typo in projectdata.cpp ( eb20860 ).
2. On develop branch, did the followings:
    1. Merged issue-801 branch ( 6e6fc2f )
    2. Updated dictionaries by editing 'correnctly' to 'correctly' manually, and run lupdate ( e4b7372 )
    3.  run `i18ntool.py build` (78498e3).
3. On develop master, did the followings:
    1. Merged issue-801 branch ( ae89044 )
    2. Updated dictionaries by editing 'correnctly' to 'correctly' manually, and run lupdate ( d278d72 )
    3.  run `i18ntool.py build` ( 39e71dc ).

Reading your comment, I've remembered that on develop branch I made a big modifications related to internationalization, to clean dictionary files. Because of this, I thought the process above will be easier, and make the commit log looks clean (I hope).

>I looked through i18ntool.py and there was no shrinkDictsInSrc function. You must have started this branch before making that modification.

I'm sorry, you are right. I've reviewed the commits, and I've remembered that I made shrinkDictsInSrc function in develop branch, so it is not in master branch nor issue-801 branch. I've understood that's why.

Anyway, can you check the commits I've made, and make sure they looks OK, please?

If so, I'll execute the following command, to push my develop and master branch to origin:

```
git checkout develop
git reset --hard inoue/develop
git push origin develop

git checkout master
git reset --hard inoue/master
git push origin master
```

Thank you,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Yes, your changes look good.  Sorry, I missed `languages/iRIC_zh_CN.ts` and `libs/guicore/project/projectdata.cpp` in 3b3adaf.
I was trying to make less work for you and ended up making more work for the both of us.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
> Hi Keisuke,
> 
> Yes, your changes look good. Sorry, I missed `languages/iRIC_zh_CN.ts` and `libs/guicore/project/projectdata.cpp` in [3b3adaf](https://github.com/i-RIC/prepost-gui/commit/3b3adaf3819c952600f0ec7b1deffdb38bef44bd).
> I was trying to make less work for you and ended up making more work for the both of us.
> 
> Thanks,
> Scott

Hi Scott,
Thanks for your reply.

No worry,
You helps me a lot, by making good commits, comments, and suggestions.

I’m going to push commits to origin, tomorrow morning.

I’m drunk, and will make mistakes if I do it now!

Thank you,

keisuke

**Comment by kskinoue0612** [comment]
I close this, because the branch is merged to develop with 6e6fc2f.

Thanks,
Keisuke

**Pull request closed without merging**
