### PR TITLE
Closes i-RIC/prepost-gui#224

### PR DESCRIPTION
**Pull request by scharlton2**
Hi Keisuke,

Hopefully this does it.  I did add one string "GridLocationNull" so you'll probably need to update the Dictionary files again.  You'll have to show me how to do that sometime.  I used these two files to do additional testing (using an empty project and File->Import->Calculation Result...):

[issue-224.zip](https://github.com/i-RIC/prepost-gui/files/1791914/issue-224.zip)

Thanks,
Scott

### CODE REVIEW

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for fixing. And, I'm sorry that my review was not perfect last time.

I've reviewed precisely this time, and I've found an issue.

The position of data showed on chart window is saved into project file with attribute "gridLocation", and the string is generated with Graph2dHybridWindowResultSetting::getGridLocationString().

But this is a problem, because currently this function returns a translated string. This means that a project file saved with iRIC GUI in English mode, can not be opened with iRIC GUI in Japanese mode.

I propose that
* You add Graph2dHybridWindowResultSetting::getGridLocationStringTranslated(), that return translated string.
* Make Graph2dHybridWindowResultSetting::getGridLocationString() returns English string always.
* Use Graph2dHybridWindowResultSetting::getGridLocationStringTranslated() with QComboBox::addItem().

How do you think? I welcome other proposals about the solution.
Thanks,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I used your recommendations to fix the translation problem.  I also needed to add Graph2dHybridWindowResultSetting::getGridLocationTranslated().  I merged in your issue-224-2 before I committed.  Hopefully this is what you intended.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your quick response.

I have a meeting outside of my office in this afternoon. I think I can
review and merge your pull request on next Monday.

Have a good weekend! :-)

Hi Keisuke,
>
> I used your recommendations to fix the translation problem. I also needed
> to add Graph2dHybridWindowResultSetting::getGridLocationTranslated(). I
> merged in your issue-224-2 before I committed. Hopefully this is what you
> intended.
>
> Thanks,
> Scott
>

**Comment by kskinoue0612** [comment]
Hi Scott,

I've tested, and found an issue, I guess.
If a project file is saved when a chart window to show cell-centered calculation result is open,
iRIC GUI crashes when trying to open that project.

I attach a file I've used to test.

[test_projects_issue-224.zip](https://github.com/i-RIC/prepost-gui/files/1801810/test_projects_issue-224.zip)

Please try to open test_cellcenter.ipro in the attached file above, and test whether the same issue occurs on your environment.

In my environment, Graph2dHybridWindowResultSetting::m_targetDataTypeInfo == 0
after calling Graph2dHybridWindowResultSetting::loadFromProjectMainFile(), and that causes the crash.

P. S. Opening test_baseiterative.ipro, test_vertex.ipro had no problem.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Sorry about all the problems with this pull request.  Thanks for your careful testing.  I think I have fixed everything this time.

P.S. I may have found an issue while testing.  It seems that sometimes (usually in debug mode) the "Case1.cgn.lock" file doesn't get removed, and when the project file is saved and reopened, it gets into a "(Not Responding)" state.  It seems to be spinning in the while loop within FileLocker::lock().  I'll try to verify and create a new issue for it tomorrow.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for the quick fix. I've tested, and made sure that now it works.
I've also tested saving project file in English iRIC GUI, and opening it in Japanese iRIC GUI.
It worked too.

Now, I've done the following things to git reository:
* Rebased your new commit to my issue-224-2 branch
* Squashed all your commits related to issue-224
* Merged it to my master branch
* Pushed my master branch to origin.

What I intended was to keep the git log clean. The code itself is just the same to yours.
I've made sure that by doing following:

git diff origin/master scott/issue-224-2

It output no difference.

Please fetch master from origin, and make your master branch the same to it, by:

git fetch origin master
git checkout master
git reset --hard origin/master

Thanks,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuike,

I think your local git repository is structured a little bit differently than mine is.  Here are the commands I ran to sync both my local repo and my github repo with the i-RIC/prepost-gui:

```
$ git checkout master
$ git remote -v
iric    git@github.com:i-RIC/prepost-gui.git (fetch)
iric    git@github.com:i-RIC/prepost-gui.git (push)
keisuke git@github.com:kskinoue0612/prepost-gui.git (fetch)
keisuke git@github.com:kskinoue0612/prepost-gui.git (push)
leon    git@github.com:Leon-Zhang/prepost-gui.git (fetch)
leon    git@github.com:Leon-Zhang/prepost-gui.git (push)
origin  git@github.com:scharlton2/prepost-gui.git (fetch)
origin  git@github.com:scharlton2/prepost-gui.git (push)
$ git fetch --all
$ git reset --hard iric/master
$ git push origin master --force
$ git log --oneline
4f9d6068 (HEAD -> master, origin/master, keisuke/master, iric/master) Merge branch 'issue-224'
c412c121 Closes i-RIC/prepost-gui#224
185f0804 Merge branch 'issue-284'
69ffe246 (keisuke/issue-284) Closes i-RIC/prepost-gui#284
a3969380 Merge branch 'issue-279'
c231d8cf Closes i-RIC/prepost-gui#279
dada5cb6 Merge pull request #277 from kskinoue0612/issue-276
```

This is a reminder to myself on how to "Force a sync from the upstream repository (iric - i-RIC/prepost-gui) to my local repository as well as my github repository (origin - scharlton2/prepost-gui)".

Thanks,
Scott

**Pull request closed without merging**
