### PR TITLE
Rivmaker improvements

### PR DESCRIPTION
**Pull request by kskinoue0612**
This pull request includes improvements to RivMaker.

## 2.4 Add capability to obtain cross section geometry/properties directly from survey data (e. g. P, E, N, Z, ID). Basically, this requires output of cross-sections from RivMaker.

1. Launch RivMaker.
2. Open test.rpro.
3. Select menu File -> Export -> River Survey Data as CSV files...
4. Select folder to export data.
5. Launch iRIC GUI and start project for CAP.
6. Open "Calculation Condition" dialog.
7. Select "Approach" group, and click on "Edit" button next to "Simple: Cross Section (X, Y).
8. Click on "Import" button, and import CSV file that you've exported in 4.

## 3.1 Add capability for vector outputs of RivMaker plots and export of .csv file.

1. Launch RivMaker.
2. Open test.rpro.
3. Open Elevation View Window, and click on "Export SVG...", and "Export CSV..." button, to export SVG file ans CSV file.
4. Open Cross Section Window, and click on "Export SVG...", and "Export CSV..." button, to export SVG file ans CSV file.

Please make sure that below:
* SVG file can be visualized with Microsoft Edge or Google Chrome.
* CSV file can be opened with Microsoft Excel.

## 3.6 Allow use of "X#" or "XS#" as cross section codes in SAC survey input files.

1. Launch RivMaker.
2. Select "Import" -> "Geographic Data" -> "SAC GUI Input File" menu.
3. Select "rivmaker_input_withxs.txt" and click on "Open" button.
4. You'll see that cross section names are "XS1", "XS2", and "XS3".

## 3.8 Add capability to include uncertainty "whiskers" on high water mark elevations as well as method to include that uncertainty value in input file.

1. Launch RivMaker.
2. Select "Import" -> "Geographic Data" -> "SAC GUI Input File" menu.
3. Select "rivmaker_input_with_uncertainty.txt" and click on "Open" button.
4. Draw base line.
5. Open "Elevation View Window".
6. You'll see uncertainty whiskers drawn for "RH-1-G", "RH-6", and "HUB-2". 

## 3.14 In RivMaker, add the capability to graphically adjust the water surface profile.

1. Launch RivMaker.
2. Open test.rpro.
3. Open Elevation View Window
4. Drag points at "X1", "X2" and "X3" to edit elevation value.

## 3.19 In RivMaker, add the capability for the user to make only a right or left bank profile and save that profile as a csv file.

1. Launch RivMaker.
2. Open test.rpro.
3. Open Elevation View Window.
4. In "Visibility Setting", check on "Left Bank HWM", and check off all others.
5. Click on "Export CSV..." button, and save CSV file.
6. Open the CSV file, and check that only Left Bank HWMs are exported.

## 3.20 Revising cross-section window and vertical cross-section window to satisfy the specifications related to SAC.

1. Launch RivMaker.
2. Open test.rpro.
3. Open Elevation View Window.
4. Check that Elevation View Window graphics is improved like below:
    * User can change the area to draw by Ctrl + Left drag (pan) and Ctrl + Middle drag (zoom)
    * User can edit Aspect ratio from tool bar.
    * When "Fix aspect ratio" is checked, when user zoom, the aspect ratio is fixed.
    * User can check On/Off "Grid", "Scale", "Aspect ratio".

[rivmaker_improvements.zip](https://github.com/i-RIC/prepost-gui/files/4985768/rivmaker_improvements.zip)

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

I think the test.rpro file you uploaded doesn't contain any data.  When I open it RivMaker looks like:

image

And when I try 2.4 I get:

image

I just got a new computer and I don't have any other .rpro files to test with.

Thanks,
Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

Sorry, I realized I needed to copy zip.exe and unzip.exe into the RivMaker Debug and Release directories.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for reviewing the pull requests.
It’s OK. Please feel free to contact me when you have problems.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Everything looks good.

I added a small fix https://github.com/i-RIC/prepost-gui/pull/764/commits/a9564c9a5c632ca9432dea8864940d4e832360e7 for the following:

WindowTitle

It's so small that as soon as appveyor checks it I'll merge this request.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for the improvement. OK, I see.

Thanks,
Keisuke

**Pull request merged**
