### PR TITLE
Closes i-RIC/prepost-gui#570

### PR DESCRIPTION
**Pull request by kskinoue0612**
You can check this by the following operations:

1. Start a new project for Nays2DH
2. Import DEM data from *.tpo file to "Elevation (m)". For example, you can get tpo file by downloading the file below.
https://i-ric.org/download-file/?dlkey=bbfa14d54dbc09e63aa4a3f74e98cdaa
r5finpt2m114_shifted.tpo is included in Tutorial 1/Exercise 1 folder.
3. Select "Elevation (m)" in object browser, and select "Add" -> "River Survey data"
   in right-clicking menu
4. Define center line by mouse-clicking, and finish definition by double-clicking.
5. Select "Build left and right bank" menu to build left bank and right bank lines.
6. Select "Generate River Survey Data" menu, and click on "OK" to generate River Survey Data.

After you've created River survey data, you can move or rotate cross section lines, and
can map DEM data to the selected cross sections, by selecting "Map points data" from
right-clicking menu.

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

When importing I27-35.riv from [I27-35.zip](https://github.com/i-RIC/prepost-gui/files/4099913/I27-35.zip) and right-clicking on the background the wrong menu is displayed:

image

And if "Generate River Survey data" is selected iRIC crashes:

Here is the latest iRIC Dev version:

image

**Comment by scharlton2** [comment]
Hi Keisuke,

It looks to me that the Crosssection is backward.  I've included some screenshots to illustrate:

image

image


image

Maybe I'm misinterpreting what is left and what is right?

[issue-570.zip](https://github.com/i-RIC/prepost-gui/files/4100556/issue-570.zip)

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for testing, and the report.
I’ll look into the code and check it.

Today and tomorrow I’m going to visit Sapporo to attend iRIC meeting, so I think I’m going to work on it next Monday.

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I've checked, and fixed the two issues you reported. Thank you.

I also made two additional commits for the followings:
* Misc improvement: The information dialog is shown after the river survey data is displayed on pre-processor window.
* Translation fix: Wrong Japanese translation is fixed.

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

After merging a few pull requests by myself, the branch for this pull request had conflicts with master branch, so I rebased.

The last four commits are the new ones.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Opening a project with an existing [RiverSurvey](https://github.com/i-RIC/prepost-gui/files/4100556/issue-570.zip) displays the wrong menu when right-clicking a cross-section.  And if 'Generate River Survey data' is selected iRIC crashes.


image

Instead of:

image

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your detailed test, and I'm sorry for the bug.
I'm going to fix this.

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I've pushed a commit to fix the bug.
Thanks,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I found one more little thing.  When opening a project containing a [RiverSurvey](https://github.com/i-RIC/prepost-gui/files/4100556/issue-570.zip) the mouse cursor is set to `Qt::CrossCursor` (I had to take a picture of the screen to include the cursor):

image

I meant to make a pull request to your issue-570 branch but I pushed directly to your branch by accident.  See what you think and merge into i-RIC/prepost-gui if its ok.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your comment. OK.

I am going to Nagoya tomorrow for business meeting, and I think I can review your commit and merge the pull request on Thursday.

Thanks,
Keisuke

**Pull request merged**
