### PR TITLE
Modified qmake files to use DESTDIR in place of QMAKE_POST_LINK commands

### PR DESCRIPTION
**Pull request by scharlton2**

### CODE REVIEW

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for the improvement!

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I looked at the latest develop branch and noticed that these changes aren't there.  Do you know how this happens?

Thanks,
Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

Sorry, I merged git@github.com:scharlton2/prepost-gui.git instead of git@github.com:i-RIC/prepost-gui.git.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

OK, I understand. No problem.

Thanks,
Keisuke

**Pull request merged**
