### PR TITLE
Closes i-RIC/prepost-gui#179

### PR DESCRIPTION
**Pull request by kskinoue0612**

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

I wasn't able to reproduce the original issue when testing 1875f0afda9a1fa8bceae438aa2d5ac2537821be (the delete item was always there).  Does the issue depend on which solver is used?  I tested using both SToRM and Mflow.

Scott

**Comment by kskinoue0612** [comment]
Hi Scott, 

I've tested with `1875f0a`, and reproduced the issue. I attach the screenshot.

screenshot

I'm afraid may be you've tried on "Boundary Condition Setting".

To reproduce this issue, you have to create grid first, and add Boundary Condition from
"Boundary Condition" node under "Grid" node.

I hope this information will help.

Thanks,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I was trying the "Boundary Condition Setting" node.  Everything seems to work when starting a project
from scratch.  But, when saving and reopening a project the Boundary Condition name is missing (#249) and when right-clicking on a Boundary Condition there is no "Delete..." menu item.

Thanks
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

OK, I see.

When you open test_249.ipro, that is attached to #179 comment, you'll have no "Delete..." menu item on Boundary Condition with the current iRIC release.

When you try with issue-179 branch, you'll have "Delete..." menu for "New Inflor BC", node.

For other nodes like "New Inflow", you can delete them from "Delete..." menu on Boundary Condition Setting items.

But anyway, I think it is better to fix the name missing problem.

Not in a hurry for this issue, so please take it easy.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Just a reminder, after rebasing your kskinoue0612/issue-179 branch with i-RIC/master I rechecked and it still loses the "Delete..." when the file is saved->closed-reopened. (You may want to rebase before you start working on this so that you don't run into the bugs that were fixed on the master branch).

By the way, we may be getting furloughed (government shutdown) tomorrow.  I will try and still communicate with you through github if this happens.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,
> Just a reminder, after rebasing your kskinoue0612/issue-179 branch with i-RIC/master I rechecked and it still loses the "Delete..." when the file is saved->closed-reopened. (You may want to rebase before you start working on this so that you don't run into the bugs that were fixed on the master branch).
> 
Thanks for reminding. I’ll rebase and recheck issue-179 branch next week.
> By the way, we may be getting furloughed (government shutdown) tomorrow. I will try and still communicate with you through github if this happens.
> 

Wow!

I believe (hope) such a thing does not really happen, but anyway, good luck!

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

You were right. "Delete..." did not show after save-> close -> reopen. Now it is fixed.

To make it easy to test and review, the branch is now rebased on to the newest commit on master branch.

Thanks,
Keisuke

**Pull request merged**
