### PR TITLE
Closes i-RIC/prepost-gui#427

### PR DESCRIPTION
**Pull request by kskinoue0612**
This is the pull request to add function to add poly lines.

This includes many refactoring commits to clean the code of polygon implementation. I thought they are beneficial, because after these refactoring, the codes related to polygons and poly lines looks very similar, and both are clean. Commits really related to poly lines are the last four.

If this looks OK, please leave a comment to say so, and please do not merge this pull request.

I'll merge this by myself, when the customer of the contract to develop this function says it is OK.

Thanks,
Keisuke

### CODE REVIEW

**Comment by kskinoue0612** [comment]
Hi Scott,

I've forgot to comment that, to build this branch, you also need to update iriclib.
That's why the appveyer check failed.
Please refer to i-RIC/iriclib#55.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Looks good.  Just a few modifications:

1. I think 'PolyLine' should be 'Polyline' in all menu items.

2. I think 'Geographic Data' menu should contain 'Polyline' submenu similar to Polygon. (already implemented in right-click menu of 'Object Browser'.

3. When creating a new Polyline, mouse-clicking two vertices and pressing Enter yields "PolyLine must have two vertices at least." message.  In `GeoDataPolyLine::definePolyLine` I think minCount should always be 2 regardless of the value of `doubleClick`.

Thanks,
Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

I noticed the same problem with Polygon.  I originally thought it was an old bug but, it doesn't seem to happen in the latest version of the Developers release.  It seems that in the Developers version that the first point cannot be undone.  In e8f3602, the last point of a Polygon can be undone and eventually crashes iRIC.

In debug mode, undoing the first point of a polygon yields the following dialog:

image


Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for reporting. I think I should have noticed this when I've fixed the bug on poly line.

I've pushed another commit to fix the bug for polygon too.
Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I've rebased issue-427 branch onto origin/master, to remove conflict. I think it is ready to be merged.
Thanks,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Do you want me to merge this or are you still waiting to hear from the customer?

Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

We've got OK from the customer, so please merge this if it seems OK to you.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

When adding a new Polygon, by clicking the first point and double-clicking the second point, I'm not getting the expected message "Polygon must have three vertices at least." Debugging yields:

image
`QPolygonF GeoDataPolygonAbstractPolygon::polygon(const QPointF& offset) const`

Note that point 1 is the same as point 2.

Since I wasn't able to reproduce this in the Developer version I think this (bug?) was introduced in this set of commits.  It seems to me that the double-click is being handled as both a double-click and two single clicks at the same time. Or maybe a call to `cleanedPolygon` was lost?

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you very much for your detailed testing.
I've fixed the issue and added a commit on the branch.

I've rebased issue-428 branch onto the new commit, so it is ready to be reviewed too.

Thanks,
Keisuke

**Pull request merged**
