### PR TITLE
Close #925

### LINKED ISSUE #925: "Fill upper", "Fill lower" checkbox in post3d window contour does not work correctly

### PR DESCRIPTION
**Pull request by kskinoue0612**
Please try with the steps below:

1. Download https://github.com/i-RIC/prepost-gui/files/6263854/issue-457-853.zip
2. Import 3dtest.cgn, from menu "Import" --> "Calculation Result".
3. Open post3d window
4. Select Contours, and select "Add" menu from right-clicking menu.
5. Please change the setting like below:
   * Check off "Automatic" check box.
   * Check off "Fill upper area" and "Fill lower area" check boxes.
   * Change Min value to 2, Max value to 8
6. Click on "Add" button in "Faces" group box
7. Click on OK button

With this branch, the setting is correctly applied, and Color fringe is drawn only for area with value between 2 and 8. Without this branch, Color fringe is drawn for the whole area.

### CODE REVIEW

**Comment by kskinoue0612** [comment]
Hi Scott,

It seems that there is a conflict in guibase.pro, so I'll rebase this branch to the new develop branch, so that you can merge the pull request.

Thank you,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

It seems to me that the "checkState" and "enabled" attributes for FaceSetting element are redundant.  Isn't 
checkState == Qt::Checked(2) equivalent to enabled?


<Contours>
  <Contours>
  <ScalarBarTitles>
    <...>
  </ScalarBarTitles>
  <ContourGroup>
    <FaceSetting checkState="2" isExpanded="false" name="Face001" enabled="true" .../>
  </ContourGroup>
</Contours>

in post3dwindowfacedataitem.cpp m_enabled isn't initialized so it's usually true but every once in a while its false.
and Post3dWindowFaceDataItem::setEnabled seems like it should call the setCheckState of  m_standardItem and possibly clone it to m_standardItemCopy.

Either way, let me know and I'll finish this one.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for the notification. I think you are right.
I'll make sure and contact you. I think (hope) I can contact you tomorrow.

Thanks,

Keisuke Inoue


2021年4月13日(火) 11:32 Scott Charlton ***@***.***>:

**Comment by kskinoue0612** [comment]
Hi Scott,

Based on your comment, I've fixed the code and pushed a commit.
Can you make sure I've understood your comment and fixed correctly?

Thank you,

Keisuke

**Pull request merged**
