### PR TITLE
Closes i-RIC/prepost-gui#573

### PR DESCRIPTION
**Pull request by kskinoue0612**
1. Create new project
2. Open Import dialog for Elevation
3. Select "ESRI Shape file (Polygon Group) (*.shp) from File Type combobox
4. Import issue-573.shp

It imports polygons quickly. Please compare the speed with importing it as independent polygons.

You also can select the polygon by mouse clicking, that was not possible with older implementation.

[issue-573.zip](https://github.com/i-RIC/prepost-gui/files/3829417/issue-573.zip)

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

I don't understand the way to use a "PolygonGroup" when adding it onto a branch of "Geographic Data".  (for example when right-clicking on "Geographic Data->Elevation (m)" and selecting "Add->PolygonGroup".)  Also, when you try to add a PolygonGroup to "Geographic Data->Reference Information" iRIC crashes.

Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for reviewing the pull request.

> I don't understand the way to use a "PolygonGroup" when adding it onto a branch of "Geographic Data". (for example when right-clicking on "Geographic Data->Elevation (m)" and selecting "Add->PolygonGroup".)

I expect that user use the function to add PolygonGroup in the following way:

1. Open an old project, that has many polygons.
2. Create a new Polygon group.
3. From right-clicking menu, select "Merge", and merge all the polygons into one "PolygonGroup".

After converting many "Polygon"s into one "PolygonGroup", user can select the polygons by mouse-clicking, so I imagined it will be convenient, particularly when there are thousands of polygons.

Also, user can use PolygonGroup to create many new polygons by hand, and group them. After creating PolygonGroup, user can add polygons, by selecting "Add" menu in right-clicking menu.

> Also, when you try to add a PolygonGroup to "Geographic Data->Reference Information" iRIC crashes.

Thanks for reporting this, and I'm sorry for the bug. I'm going to fix this, and add a commit to the branch.

Thanks,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Thanks for your explanation, I now understand.  I now have an additional question. How are overlapping polygons within the same PolyGroup handled?  It seems that there is no way to move a polygon up or down.

I also found a problem that occurs when a polygon within a polygongroup is selected and the attributes are mapped that the attributes of the selected polygon are not mapped.

Steps to reproduce:

1. Open [3triags.zip](https://github.com/i-RIC/prepost-gui/files/3860940/3triags.zip)

image

2. Select Geographic Data->Elevation (m)->PolygonGroup1

image

3. Select the dark blue triangle

image

4. Grid->Attributes Mapping->Execute... and select 'Elevation (m)' and press OK

5. Uncheck 'Geographic Data' (again)

image

6. Select and Recheck 'Geographic Data'

image

7. Grid->Attributes Mapping->Execute... and select 'Elevation (m)' and press OK (again)

8. Uncheck 'Geographic Data' (again)

image


And it seems that when exporting polygongroups that contain holes that the holes are missing when imported:

image

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your response and additional detailed report.

# Bug fixes and improvement

I've pushed several additional commits, so let me explain.

## Bugs that you've reported

> Also, when you try to add a PolygonGroup to "Geographic Data->Reference Information" iRIC crashes.

I've fixed the issue in https://github.com/i-RIC/prepost-gui/pull/633/commits/0be5f95da646b3a87f424459ae3440ad02a1dc53.

> I also found a problem that occurs when a polygon within a polygongroup is selected and the attributes are mapped that the attributes of the selected polygon are not mapped.

I've fixed the issue in https://github.com/i-RIC/prepost-gui/pull/633/commits/bf18e53488d39a0fb9ea5a293b6b41ffc7edf52d.

> And it seems that when exporting polygongroups that contain holes that the holes are missing when imported

I've fixed the issue in https://github.com/i-RIC/prepost-gui/pull/633/commits/47e7d8131f3e2aaa5a33b920c5c9fc5132756144.

Thanks for reporting them.

When I was checking, I noticed several other issues, so I've also fixed them as below:

## Undo issue

When user do the following operation, iRIC crashes.

1. Select a polygon
2. Do some modification (for example, move or add vertices)
3. Deselect the polygon
4. Press Ctrl + Z key to undo

It is fixed in https://github.com/i-RIC/prepost-gui/pull/633/commits/3498bbb9797b2b3479eb4efc326f3272c74b36b0.

After fixing, undo stack is cleared when user deselect a polygon.

## Color setting for selected polygon

Color setting (Custom color and opacity) for selected polygon is not applied correctly.

It is fixed in https://github.com/i-RIC/prepost-gui/pull/633/commits/c212fda3f061d198ee5321e69355f00226fe842e.

## "Color Setting" menu is added

Like for "Polygon", "Color Setting" menu is now added to right-clicking menu.

It is fixed in https://github.com/i-RIC/prepost-gui/pull/633/commits/0aefae6880cd152ac14088962fbdc72622af14f6 and https://github.com/i-RIC/prepost-gui/pull/633/commits/b2bf85afed896352e1e8067dcc74ddc5ecd72b9b.

## "PolygonGroup" menu in "Geographic Data" menu on menu bar

Just like for other geographic data, now "PolygonGroup" menu is added to "Geographic Data" menu on menu bar.

I know most people use right-clickig menu instead of menu bar, but for compatibility with other geographic data types, I added the menu.

It is fixed in https://github.com/i-RIC/prepost-gui/pull/633/commits/142d890c0e3882b55c2024841daf1c7281f59ebc.

# About mapping behavior for overlapped polygons

> I now have an additional question. How are overlapping polygons within the same PolyGroup handled? It seems that there is no way to move a polygon up or down.

Thanks for the comment. I recognize that it is an important point.

The code to map polygons is like below:

https://github.com/kskinoue0612/prepost-gui/blob/issue-573/libs/geodata/polygongroup/private/geodatapolygongroupnodemappert_detail.h#L33-L41

The important function of GeoDataPolygonGroup::polygonsInBoundingBox() is to call geos::index::quadtree::Quadtree::query(), so order of polygons in the returned vector is arbitrary. You can see the actual code in below:

https://github.com/kskinoue0612/prepost-gui/blob/issue-573/libs/geodata/polygongroup/geodatapolygongroup.cpp#L109

And as you've commented, there is no way to move a polygon up or down.

That's because we expect that the main use case of "PolygonGroup" is that user import thousands or tens of thousands of polygons from shape files, to map them to grid. For example in Japan, building polygons and land use polygons are generally available.

And as you can guess, such data does not contain overlapped polygons. That's why I did not include function to move up or down polygon in this release. I mean, it will not be so important for the first release of PolygonGroup.

I want to merge PolygonGoup function when there is no critical issue, so that Kazutake, Yasu, and Jon can test it. Maybe they will give feedback, including requests for function to move up and down, and then we can discuss which improvements have high priority.

Anyway, I agree that it is a major point user should be noticed, that there is no move up / down function for PolygonGroup, so I'm going to note it in the user manual.

Thank you for your contributions,

Keisuke Inoue

**Pull request merged**
