### PR TITLE
Breakline div

### PR DESCRIPTION
**Pull request by Leon-Zhang**
Add menu item and getInt input.

### CODE REVIEW

**Comment by kskinoue0612** [comment]
Scott, I've found that this pull request still has a bug. Please do not test now.

**Comment by kskinoue0612** [comment]
I've tested the code.

As Scott commented, the code contains a bug now.
Because of that, the re-dividing looks to be working correctly at the first time, but when I try re-dividing again, it does not work correctly. When I tested, sometimes the breakline disappeared, and sometimes iRIC crashed.

But, the first re-dividing looks good. You are near the goal, Leon! Please check and fix the bug.

**Comment by Leon-Zhang** [comment]
Hello Scott, Inoue,

I have fixed the bug and tested, it won't crash and able to divide multiple times, but seems sometimes(very random) the divided line looks not correct.

Here is the ipro file for test:
https://drive.google.com/file/d/0B33dCE5TlvtqYUJvdzBnakZUUm8/view?usp=sharing

Thanks,
Leon

**Comment by kskinoue0612** [comment]
Thank you very much, Scott!

**Comment by kskinoue0612** [comment]
Scott, thank you for reviewing!

Leon, I've reviewed your code, and it seems OK. Thanks.

To finish this branch, I've added some modifications, like slightly changing menu caption, adding Japanese translation etc. and pushed to my repository.

https://github.com/kskinoue0612/prepost-gui/commits/breakline_div

And, now the branch has become split to so many commits, I've squashed the commits, and removed
some modifications not related to the topic. that branch is pushed to my repository with name breakline_div_squashed, that contains only one commit:

https://github.com/kskinoue0612/prepost-gui/commit/040d52e57f93c5bce94ba41d4870586aa0f9150f

If you think it is OK, please do the following operation.

> git origin add inoue https://github.com/kskinoue0612/prepost-gui.git
> git fetch inoue
> git checkout breakline_div
> git reset --hard inoue/breakline_div_squashed
> git push -f leon breakline_div

These operations will make your breakline_div branch the same to my breakline_div_squashed branch.

Then, I'll merge this pull request.

Thanks,

Keisuke Inoue

**Comment by Leon-Zhang** [comment]
Hi Inoue, I have done the branch, please merge.

**Comment by scharlton2** [comment]
Hi Keisuke and Leon,

I think those commands should be:

> git remote add inoue https://github.com/kskinoue0612/prepost-gui.git
> git fetch inoue
> git checkout breakline_div
> git reset --hard inoue/breakline_div_squashed
> git push -f XXX breakline_div

Where XXX is probably origin depending on where you cloned from.  To check run:
> git remote -v

and select the one that has:

`https://github.com/Leon-Zhang/prepost-gui` or `git@github.com:Leon-Zhang/prepost-gui.git`

Leon, you might want to wait and see if Keisuke agrees with this.

Scott

**Comment by kskinoue0612** [comment]
Hi, Scott and Leon

Sorry, I was in a travel today, and did not have time to check mails until now.

Scott, thanks for your comment. Yes, "git remote", not "git origin".

Leon, as you'll see, your breakline_div branch is not changed. Please try again following Scott's comment.

Thanks,
Keisuke

**Comment by Leon-Zhang** [comment]
Hi,

Scoot, I just done as what you suggested.
Inoue, I have double checked, there is one commit left in branch, please merge.

Leon

**Pull request merged**
