### PR TITLE
Close #589

### LINKED ISSUE #589: Add "All importable files" filter to Grid import dialog
Add "All importable files" filter to Grid import dialog, so that user can select file to import easily.

### PR DESCRIPTION
**Pull request by kskinoue0612**
Please test this with the following steps:

1. Launch iRIC GUI
2. Start new project for Nays2DH
3. Create grid. For example, You can select "Multifunction Grid Generator" as the grid generator, and click on "Create Grid" to create grid easily.
4. Export grid to files, like *.cgn, *.csv.
5. Try to import Grid from files exported in 4., with "All importable files" file filter setting, and make sure it succeeds.

Please note that if you want to try with grid importer plugins, you'll need to copy grid importer plugins to appropriate folders.

### CODE REVIEW

**Comment by kskinoue0612** [comment]
Hi Scott,

This branch has conflicts with developer branch, because of i18n dictionaries.
Please test the branch, and if it seems OK, please post a comment. Then, I'll merge this branch, by resolving the conflict locally.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I was able to export (LandXml files *.xml) and (VTK files *.vtk) but had no way to import them.

Also, when exporting grid.cvs I set the File name: to grid.cvs and it appended another cvs and saved it as grid.cvs.cvs.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for taking your time for reviewing the pull request.

> I was able to export (LandXml files *.xml) and (VTK files *.vtk) but had no way to import them.

That's true. The list of file formats for import is not the same to that for output. The objective of this pull request is to import grids easily using "All importable files" filter, so you can just ignore them.

> Also, when exporting grid.cvs I set the File name: to grid.cvs and it appended another cvs and saved it as grid.cvs.cvs.

Not sure, but I'm afraid maybe you exported grid with file name "grid.cvs", instead of "grid.csv", selecting the filter "iRIC Grid CSV files (*.csv)". I've tried, and when I input "grid.csv" as the file name, it was saved to "grid.csv". When I've input "grid.cvs", it was saved to "grid.cvs.csv". I think it is a valid behavior.

Please make sure.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Sorry, yes you're right I did type grid.cvs instead of grid.csv.  Go ahead and merge.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for making sure.
OK, I'll merge the branch manually.
Thanks,

Keisuke

**Pull request merged**
