### PR TITLE
Close #737, #738

### LINKED ISSUE #737: ComboBox to switch cross section is added to dialog for editing cross section attributes for SAC
When SAC solver is used, on dialog to edit grid attributes "Cross Section", a Combo box is added so that user can edit values without repeating opening and closing the dialog.

### PR DESCRIPTION
**Pull request by kskinoue0612**
# Issue #737

You can test with the following procedure.

1. Open issue-737.zip
2. Select Grid / Node attributes / Crosssection in Object Browser of Pre-processing Window
3. Select a node, and click on "Edit value" in right-clicking menu.
4. You'll see a dialog with "Target" combo box on the top, and you can switch between the cross sections without opening and closing the dialog.

# Issue #738 

You can test with the following procedure.

1. Open issue-738.zip
2. Select Grid / Node attributes / Crosssection in Object Browser of Pre-processing Window
3. Select a node, and click on "Edit value" in right-clicking menu. Please make sure that roughness values are 0.01 at all nodes.
4. Select nodes, and from right clicking menu, select "Edit value by specifying ratio".
5. On the dialog check on "Simple Roughness (NVAL(1))", and input "3", and click on OK.
6. Please repeat Operation 3, and make sure that roughness values are 0.03 at the edit target nodes.

[issue-737.zip](https://github.com/i-RIC/prepost-gui/files/4813195/issue-737.zip)
[issue-738.zip](https://github.com/i-RIC/prepost-gui/files/4813196/issue-738.zip)

### CODE REVIEW

**Comment by kskinoue0612** [comment]
Hi Scott,

The appveyor reports that build failed, but it seems wrong. Actually, building 819a9f9 succeeded. You can check from the following URL:
https://ci.appveyor.com/project/i-RIC/prepost-gui/builds/33687170

The message that "All checks have failed" comes from the fact that I've closed the previous pull request (#740), and the following build was canceled.
https://ci.appveyor.com/project/i-RIC/prepost-gui/builds/33687142

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I think there's a bug having to do with the "Edit value by specifying XXX ..." functions when applied to functional values.  When selecting "Simple: Cross Section(X, Y) / X" the ratio is applied to Y instead of X.  See the following sequence (the ratio 2 is applied to Y twice).  I got similar results when using the "difference" method.

# Issue #738 
[issue-738.zip](https://github.com/i-RIC/prepost-gui/files/4813196/issue-738.zip)

image


image


image


image


image


Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for the detailed test, and I'm sorry for the bug.
I'll check and fix it.

Thanks,

Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I've fixed the bug, and pushed a commit.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
image

image
Press OK

image
Press OK, Press OK

image

image
Press OK

image

image
Press Edit

image

**Comment by kskinoue0612** [comment]
Hi Scott,

I've checked the code, and knew that the issue you reported in https://github.com/i-RIC/prepost-gui/pull/743#issuecomment-649042744 was caused by https://github.com/i-RIC/prepost-gui/pull/743/commits/e934ef0d2bef923cbf83e9db26659b89a3decf40.

So, I'm going to do the following tasks.
* Close this pull request, without merging.
* Create a new branch and pull request that fix only #738, so that you can check and merge independently.
* I'll try to make branch to close #737, that does not contain bug that you reported.

Thanks,

Keisuke

**Pull request closed without merging**
