### PR TITLE
Closes i-RIC/prepost-gui#426

### PR DESCRIPTION
**Pull request by kskinoue0612**
After opening the issue-426.ipro in the zip file attached to this pull request, please open cross-section window for the river survey data.

You'll see the positions of cross points between cross section line and polylines.

[issue-426.zip](https://github.com/i-RIC/prepost-gui/files/2679866/issue-426.zip)

### CODE REVIEW

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for testing, and I'm sorry for the issue.
I've pushed another commit to fix the issue. Please try it.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

In `void GeoDataRiverSurveyCrosssectionWindowGraphicsView::drawPolyLineCrossPoints(QPainter& painter)` targetPoint is null when unchecking RiverSurvey 2 in Crosssection Window:

image

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for reporting the issue.
I've fixed, and pushed another commit.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Please see kskinoue0612/prepost-gui#8.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your support.

Keisuke

**Pull request merged**
