### PR TITLE
Closes #471, #624, #625

### LINKED ISSUE #471: Improve KML export function
Currently, when exporting KML files, the elevation for each polygon node are the same for a cell.
This makes the water surface looks not smooth.

Improve this to make the water surface looks smooth.

### PR DESCRIPTION
**Pull request by kskinoue0612**
This pull request closes the following three issues:
* #471 
* #624 
* #625 

https://github.com/i-RIC/prepost-gui/commit/8b264041f444417a4c07ff5e79ba9d5352b10eae contains modifications not only for #471, but also a misc enhancement that when only one time step is exported to KML file, <TimeStep /> tag is not output, so that needless time slider is hidden on Google Earth.

Please use the following file to test.

[issue-471-624-625 .zip](https://github.com/i-RIC/prepost-gui/files/3762031/issue-471-624-625.zip)

To make the file small, calculation result is not included, so please run model before checking.

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

Can you give me the coordinate system for the test?

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for working on the pull request.
Please use "EPSG: 2454: JGD2000 / Japan Plane Rectangular CS XII" for coordinate system.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I wasn't able to view the results of the example you supplied in Google Earth.  This was probably due to the size of the output.

For reference, I added a smaller example [N2F_2-1.zip](https://github.com/i-RIC/prepost-gui/files/3796199/N2F_2-1.zip) along with some images.

Pre issue [output.zip](https://github.com/i-RIC/prepost-gui/files/3796203/output.zip):
Orig

[issue-471-624-625.zip](https://github.com/i-RIC/prepost-gui/files/3796216/issue-471-624-625.zip):
Issue-471-624-625

**Comment by kskinoue0612** [comment]
Wow! This is a very good example!
Thanks for this.

Keisuke Inoue

**Pull request merged**
