### PR TITLE
Closes i-RIC/prepost-gui#432

### PR DESCRIPTION
**Pull request by kskinoue0612**
## Change to iRIC GUI structure

This pull request contains a big change to the structure of iRIC GUI.

Hydraulic data used to be a data that can be imported as part of geographic data.
The only hydraulic data implemented is water elevation, and it used to be a part of river survey data. When importing water surface elevation, use had to import river survey data in advance.

But now hydraulic data is now an independent data. Because of that:
* Now user can import water elevation before importing river survey data.
* When user delete river survey data, water elevation data is not removed at the same time.

## Functions added

User can import multiple water elevation at the same time.
Please test the following:

1. Import I27-35.riv from menu "Import" -> "Geographic Data" -> "Elevation"
2. Import I27-35_H27-29.csv from menu "Import" -> "Hydraulic Data" -> "Water Elevation"
3. Open cross section window for the river survey data
4. You'll see that multiple Water Elevation is shown for each cross-section.

You can edit the water elevation setting like below:

* You can switch on/off the water elevation using check boxes.
* You can edit name by double clicking the name.
* You can edit water elevation value by double clicking the value.
* You can edit color by clicking.

[issue-432.zip](https://github.com/i-RIC/prepost-gui/files/2679999/issue-432.zip)

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

This has the same problem as Pull request #463.  After following your steps and unchecking River Survey 1 in the Crosssection Window iRIC crashes.  Maybe both PRs use the same code?

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for testing.
I've checked, and made sure that issue-432 branch does not include code to show cross points on river survey cross-section window. This pull request add function to show multiple water elevations on cross section windows.

Can you try again after rebuilding?

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I'm still reproducing:

image

in `GeoDataRiverSurveyCrosssectionWindowGraphicsView::drawWaterSurfaceElevation`:
[m_parentWindow->target() ](https://github.com/kskinoue0612/prepost-gui/blob/issue-432/libs/geodata/riversurvey/geodatariversurveycrosssectionwindowgraphicsview.cpp#L466) is null.

With the following call stack:
```
 	Qt5Cored.dll!QString::QString(const QString & other) Line 878	C++
>	iricGdRiversurvey.dll!GeoDataRiverSurveyCrosssectionWindowGraphicsView::drawWaterSurfaceElevation(int index, QPainter & painter, const QMatrix & matrix) Line 466	C++
 	iricGdRiversurvey.dll!GeoDataRiverSurveyCrosssectionWindowGraphicsView::drawWaterSurfaceElevations(QPainter & painter, const QMatrix & matrix) Line 458	C++
 	iricGdRiversurvey.dll!GeoDataRiverSurveyCrosssectionWindowGraphicsView::paintEvent(QPaintEvent * __formal) Line 107	C++
 	Qt5Widgetsd.dll!QWidget::event(QEvent * event) Line 8831	C++
 	Qt5Widgetsd.dll!QFrame::event(QEvent * e) Line 540	C++
```

I'll try rebuilding overnight and try again.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

I’m sorry, I’ve just understood what you wanted to say now. You are right,
#464 has an issue with null target.

I’ll fix it and cpush another commit later.
Thanks,

Keisuke

2018年12月19日(水) 14:43 Scott Charlton <notifications@github.com>:

**Comment by kskinoue0612** [comment]
Hi Scott,

I've fixed the bug that when river survey data checkbox is checked off, iRIC GUI crashes.

Thanks,
Keisuke Inoue

**Comment by kskinoue0612** [comment]
Hi Scott,

Because I've merged #463, now it has conflict and can not be merged automatically.
I'll rebase issue-432 branch on the new master branch.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Please see pull request kskinoue0612/prepost-gui#9.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,
I merge this pull request by myself, because we plan to release iRIC next time tomorrow.
If you've found additional issues related to this function, please create a new issue to report it.

Thanks,
Keisuke

**Pull request merged**
