### PR TITLE
Closes i-RIC/prepost-gui#506

### LINKED ISSUE #506: Improve Google Earth KML export function so that we do not need to input lonlat of background image
Currently, we have to input the lonlat of left bottom and right bottom for background image.
This input was needed before defining coordinate system, but now we have proj.4 function implemented in iRIC.

We should use coordinate system information to export KML, so that we do not need to input lonlat of background image.

### PR DESCRIPTION
**Pull request by kskinoue0612**
Closes #506.

When you open the issue-506.ipro attached below, you can export KML from "Continuous Snapshot / Movie / Google Earth Export" menu, without importing background image..

[issue-506.zip](https://github.com/i-RIC/prepost-gui/files/3106006/issue-506.zip)

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

I tried importing the kml/images into Google Earth and it seems that the orientation isn't quite right.  Maybe I'm doing something wrong.

Google Earth with nothing turned-on:

Screenshot 2019-04-23 16 11 26

Google Earth with "Google Earth KML for street view" turned-on:

Screenshot 2019-04-23 16 11 35

Google Earth with "Continuous Snapshot / Movie / Google Earth Export" turned-on:

Screenshot 2019-04-23 16 11 14

I think it's upside down and rotated 90 degrees

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for reporting.
I’ll check it again.

Thanks,

Keisuke

2019年4月24日(水) 7:22 Scott Charlton <notifications@github.com>:

**Comment by kskinoue0612** [comment]
Hi Scott,

Today I've tested again, and I did not succeed to reproduce the issue that you've reported. The function worked correctly.

I attach the screenshot, and the files I've exported.

How I've exported the files is as follows:

1. Open issue-506.ipro
2. Open menu File -> Continuous Snapshot / Movie / Google Earth Export...
3. On "Introduction" page, click on "Next" button ,
4. On "Window Selection" page, click on "transparent" button in "Background" group box, and click on "Next" button
5. On "File Properties" page, click on "Next" button
6. On "Movie Properties" page, click on "Next" button
7. On "Timestep Setting" page, click on "Next" button
8. On "Output to the Google Earth" page, click on "Output to the Google Earth" checkbox, and click on "Next" button
9. On "Confirm the result" page, click on "Finish" button

Please let me know if you've noticed the difference with your operation.

I think that it will be helpful if you upload the KML file you've got.

[output.zip](https://github.com/i-RIC/prepost-gui/files/3126292/output.zip)

screenshot

Thanks,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I got close to the same results as last time:

image

Your version displayed correctly.

Here are my results:

Original  version:
[original.zip](https://github.com/i-RIC/prepost-gui/files/3129294/original.zip)

Latest version:
[latest.zip](https://github.com/i-RIC/prepost-gui/files/3129298/latest.zip)

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for uploading the files. Now it is holidays in Japan, and I am
traveling now. I think I can check your files on May 2nd.

Thanks,

Keisuke

2019年4月30日(火) 6:42 Scott Charlton <notifications@github.com>:

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks to the file you've uploaded, I think I've succeeded to figure out the bug, and fixed it.
Please check that now it works on your environment too.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

It's working correctly now.  I accidentally pushed some changes to some of the English directly to your fork (didn't think I could that).  Hopefully, it doesn't mess anything up.  It seems like a lot of changes for only three strings.  Maybe I have a slightly different version of Linguist?

Let me know if I broke anything.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for reviewing.

I've roughly reviewed the commit you made, and it seems OK to me. To make sure, I'll merge the pull request after testing. I think I can merge tomorrow. I'm in my hometown Tsukuba now.

The reason that diff contains a lot of changes is that when we modify source code and the modification do not changes strings to be translated, we usually do not run lupdate to update *.ts files. As you've seen, *.ts files contains <Location /> tag that contains information about the line number on which the string appears. Because of this, when you run lupdate, the diff of *.ts files often contains many changes on <Location /> tag lines, that are caused by older commits.

You are doing right thing. Please don't worry.

Thanks,
Keisuke

**Pull request merged**
