### PR TITLE
Closes i-RIC/prepost-gui#105

### PR DESCRIPTION
**Pull request by kskinoue0612**
Now break lines can crosses polygons (refinement polygons, hole polygons).

Please note that if the break lines divide polygons to multiple areas, the result is ambiguous.
That is a limitation of the function, currently. So test3_ok.ipro, to test8_ok.ipro in tests_issue105.zip attached to #105 will generate grids, but the result is not something we expect.

A message box about this limitation is shown when user setup break line that crosses polygons.

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

I think everything looks good except for when a hole polygon is split (divided).  Would it be possible (or not too difficult) to split the breakline into three parts when it splits a hole polygon and remove the breakline that is interior to the hole polygon before generating the triangles?

Maybe it is too difficult.

Thanks,

Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for your comment.

I'm not sure, but maybe possible.
I'll do some try.

Thanks,

Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I did some try to improve handling hole polygons, and pushed the issue-105-hole-improvement branch. 

https://github.com/kskinoue0612/prepost-gui/tree/issue-105-hole-improvement.

It worked well with test7_ok.ipro, but when tried with test8_ok.ipro, iRIC GUI crashed. To me, it seems to be difficult to implement something that run safely with any cases.

Do you have some better idea?

**Comment by kskinoue0612** [comment]
Hi Scott,

I'm afraid maybe you've forgotten about this issue.
Can you give me feedback about my last comment, or just merge the pull request?

I know this pull request is not a perfect solution, but I believe it is an improvement.

Thanks,
--
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Yes I got distracted and forgot to come back to this issue.  I ran through all the test cases (in both release and debug) on the issue-105-hole-improvement branch and had no problems.  Was it reproducible for you?  Also, for the GEOS library, what documentation do you use? Is it the javadocs at [http://www.tsusiatsoftware.net/jts/javadoc/com/vividsolutions/jts/geom/packagesummary.html](http://www.tsusiatsoftware.net/jts/javadoc/com/vividsolutions/jts/geom/packagesummary.html).

I'll merge this in but I think you might want investigate what was causing the problem with the issue-105-hole-improvement branch.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for your information.
On my environment, iRIC crash was reproducible. When I'm back to office, I'll try again, and share stack trace.

For document, I usually refer to the following.

http://geos.osgeo.org/doxygen/

Thanks,

Keisuke

**Pull request merged**
