### PR TITLE
Closes #736

### LINKED ISSUE #736: Add copy and paste function to Functional calculation condition dialog
Add copy and paste function to functional calculation condition dialog, so that user can copy and paste values between iRIC and Excel.

### PR DESCRIPTION
**Pull request by kskinoue0612**
You can test this pull request with the following precedure.

1. Start a project for CAP.
2. Open calculation condition dialog.
3. Select "Aprpoach" group, and click on "Edit" button next to "Simple: Cross Section (X, Y).
4. Dialog with message "You can copy and paste the values, with short cut Ctrl + V and Ctrl V" is shown.
5. On the dialog, you can use short cut key "Ctrl + C", "Ctrl + V" to copy or paste values to / from clipboard.

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

I just added Ctrl+Insert and Shift+Insert keyboard shortcuts.  So simple I didn't think you would need to check.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for the improvement.

I’ve noticed that I‘ve made a pull request to merge to master branch, but I should have made a pull request against develop branch.

I will merge this branch to develop branch manually.
Thanks,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I'm glad you noticed because I didn't.  I was just waiting for the appveyor to complete.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks you for your response.
Now I’m on the train, and will work on it in an hour.
Thanks,

Keisuke

**Comment by kskinoue0612** [comment]
I close this pull request, because I've merged to develop branch.

Thanks,
Keisuke

**Pull request closed without merging**
