### PR TITLE
Closes i-RIC/prepost-gui#431

### PR DESCRIPTION
**Pull request by kskinoue0612**
This is a pull request with additional modification to https://github.com/i-RIC/prepost-gui/pull/443.

In the last pull request, user could edit the cross section shape from dialog, but now it is also possible to edit with mouse operations. From the mouse operation, the slope fraction is selected from the values specified on "River Survey Data" tab on "Preference" dialog .

If user want to edit precisely, user can open the dialog from right-clicking menu.

Please use https://github.com/i-RIC/prepost-gui/files/2547021/test_issue-431.zip for testing.

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

At first I didn't know what you meant when you said:
> If user want to edit precisely, user can open the dialog from right-clicking menu.

But now I think that you meant to have both `editFromSelectedPointAction()` and `editFromSelectedPointWithDialogAction()` on the m_rightClickingMenu of `GeoDataRiverSurveyCrosssectionWindowGraphicsView`.

for example:
```
diff --git a/libs/geodata/riversurvey/geodatariversurveycrosssectionwindowgraphicsview.cpp b/libs/geodata/riversurvey/geodatariversurveycrosssectionwindowgraphicsview.cpp
index cf0e4b27..4680609c 100644
--- a/libs/geodata/riversurvey/geodatariversurveycrosssectionwindowgraphicsview.cpp
+++ b/libs/geodata/riversurvey/geodatariversurveycrosssectionwindowgraphicsview.cpp
@@ -131,6 +131,7 @@ void GeoDataRiverSurveyCrosssectionWindowGraphicsView::setupMenu()

                m_rightClickingMenu->addSeparator();
                m_rightClickingMenu->addAction(m_parentWindow->editFromSelectedPointAction());
+               m_rightClickingMenu->addAction(m_parentWindow->editFromSelectedPointWithDialogAction());
                m_rightClickingMenu->addAction(m_moveAction);
                m_rightClickingMenu->addAction(m_parentWindow->deleteAction());
        }
```

Otherwise everything else looks good.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for reviewing and your comment.

I understand your suggestion, but the current behavior is basically what my customer and I thought OK. Let me explain the detail.

On cross section window, when user select a point and open right-clicking menu, "Edit cross section from selected point" is shown, and user can start editing with mouse operation. When in mouse editing mode, if user open right-clicking menu, it has only one item "Edit from Dialog", and clicking on this, user can enter dialog editing mode.

My customer and I agreed that most of user prefer editing by mouse because it is much easier to operate, and user use dialog edit mode only when they want to do precise editing. That's why the menu to enter dialog edit mode is not shown on right-clicking menu by default.

But reading your comment, I thought that currently the way to enter dialog edit mode is hard to find. So I've updated the help information message, to inform how to enter dialog edit mode.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

This looks good.  I still don't know how to fix these conflicts.  You can go ahead and close this pull request.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for reviewing. I'm going to resolve conflicts and merge by myself.

Thanks,
Keisuke

**Pull request merged**
