### PR TITLE
Closes i-RIC/prepost-gui#345

### PR DESCRIPTION
**Pull request by kskinoue0612**
This function adds new grid creating algorithm "Create grid shape solving Laplace equation". 

The usage of the new grid algorithm is already in the document, so please refer it to know how to use it.
http://iric-gui-user-manual.readthedocs.io/en/latest/

The attached file contains sample grids created with the new algorithm.

Thanks,
Keisuke

[issue-345.zip](https://github.com/i-RIC/prepost-gui/files/2976006/issue-345.zip)

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

I checked out your laplace_en branch on https://github.com/kskinoue0612/gui_user_manual and built the html and got this (still in japanese):

image

Also, it looks like a couple of images weren't checked in:
```
C:\gui_user_manual\source\04\05\01_07_laplace.rst:25: WARNING: image file not readable: 04\05\images/laplace_example_grid1.png
C:\gui_user_manual\source\04\05\01_07_laplace.rst:32: WARNING: image file not readable: 04\05\images/laplace_example_grid2.png
C:\gui_user_manual\source\04\05\01_07_laplace.rst:39: WARNING: image file not readable: 04\05\images/laplace_example_grid3.png
C:\gui_user_manual\source\04\05\01_07_laplace.rst:46: WARNING: image file not readable: 04\05\images/laplace_example_grid4.png
```

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Wow! I’m sorry.
I’m sure I can fix this soon. Hopefully tomorrow.
Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I've updated the English documentation.
Now you can read the documentation on readthedocs.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I may have found a bug but I haven't been able to reproduce it.  I'm going to try to reproduce it, but if I'm unable to, I will merge it.  

It seemed to display a previous grid when opening a file with a laplace grid.

I'll finish this as soon as possible.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your response. I understand. It’s OK.

I’m sorry, I haven’t share the information, but Kazutake and I have decided
that we are going to release iRIC on April 5th next time.

I’m going to work on the issue on polygon today.

Thanks,

Keisuke

2019年3月27日(水) 12:32 Scott Charlton <notifications@github.com>:

**Comment by scharlton2** [comment]
Hi Keisuke,

I found a minor problem that exists when undoing the "Build Left bank and Right bank lines".  It occurs in both of the Laplace and Poisson grid creating algorithms.  I think that the "Build Left bank and Right bank lines" needs to be undone or that the undo list needs to be cleared after the "Build Left band and Right bank lines" is executed.  Note that this problem occurs when no River Survey data has been imported.

Here are some images that demonstrate the problem:

image

image

image

image

Press undo 5 times:

image


Thanks,
Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

I also found a typo and created a pull request for you. Please see kskinoue0612/prepost-gui#10.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your pull request. I've added another commit to update Japanese dictionary, and merged your pull request.

I agree that we should clear undo list after building left bank and right bank lines. I'll work on that.
Thanks,

Keisuke

**Pull request merged**
