### PR TITLE
Issue 154

### PR DESCRIPTION
**Pull request by scharlton2**
Hi Keisuke,

Here's the latest CellCenter version.  You can pull it if you think it's ok without the 'Contour Figure' display option.

Thanks,
Scott

### CODE REVIEW

**Comment by kskinoue0612** [comment]
Hi Scott,

Sorry for late response.

To make it easier to review, I've squashed the commits to one, and rebased to master.

https://github.com/kskinoue0612/prepost-gui/commit/7f747be11b762f2bac48bcee7698a8639ee750fd

And I've noticed that the modification contains something that is not related to cell-centered visualization, so I've split the branch to two branches, to make them cleaner:

* issue-154-divided (https://github.com/kskinoue0612/prepost-gui/commit/9e00b0ba6ea6ffc26cc2a26b0ea90579b1ef05d2)
* titlebar-cleanup (https://github.com/kskinoue0612/prepost-gui/commit/4fc91e55752d6401edf666af2fc1081387bf6858)

Please check, and if it is OK, please do the followings:

* Make your issue-154 branch the same with issue-154-divided, with the following commands:
```
git fetch inoue issue-154-divided
git checkout issue-154
git reset --hard inoue/issue-154-divided
git push origin issue-154
```
Then, I'll merge the pull request.

* Register the issue about scalarbar output, and make another pull request using the titlebar-cleanup branch (please rename the branch as you like, because it is a temporally named by me).

Thanks,

Keisuke Inoue

**Comment by scharlton2** [comment]
Hi Keisuke,

You forgot to add the new files:

    libs/post/post2d/datamodel/post2dwindowcellscalargroupdataitem.cpp
    libs/post/post2d/datamodel/post2dwindowcellscalargroupdataitem.h
    libs/post/post2d/datamodel/post2dwindowcellscalargrouptopdataitem.cpp
    libs/post/post2d/datamodel/post2dwindowcellscalargrouptopdataitem.h
    libs/post/post2d/iricactivecellfilter.cpp
    libs/post/post2d/iricactivecellfilter.h

into [issue-154-divided](https://github.com/kskinoue0612/prepost-gui/tree/issue-154-divided).

This turned out to be a good thing since it forced me to learn how
to squash and rebase for myself.  I'll try to remember to do this from
now on for all of my pull requests.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your comment, and sorry for my mistake.

I'll stay at Sapporo until Friday, so I'll fix and push issue-154-divided branch next Morning.

Thanks,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

You don't need to do anything, I've already split, squashed and rebased into the following
branches: 
* issue-154 (https://github.com/scharlton2/prepost-gui/commit/41d08b683b7f21b90e70dcb321d188182db0b023)
* issue-199 (https://github.com/scharlton2/prepost-gui/commit/03c478ca374424235dbdb5c44dcb60c4ae2e3279)

And created the new pull request (https://github.com/i-RIC/prepost-gui/pull/200)

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Thanks, Scott!

**Pull request merged**
